#!/usr/bin/env python3
"""Render docs/audits/metrics/report.md and index.html from the dated
snapshots produced by analyze.py. Stdlib only — no dependencies.

The report is tables (newest snapshot last, so columns read left→right in
time); the dashboard is a single self-contained HTML file with inline-SVG
trend lines, same spirit as tools/repo-metrics/.

Usage: python3 tools/audit-metrics/render.py [--repo-root PATH]
"""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

MAX_COLUMNS = 8  # most recent snapshots shown in report tables

SEVERITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

CATEGORY_LABELS = {
    "architectural_debt": "Architectural debt",
    "edge_case_failures": "Edge-case failures",
    "scalability_bottlenecks": "Scalability bottlenecks",
    "doc_test_gaps": "Doc & test gaps",
    "operational_security": "Operational / security",
}

HYGIENE_LABELS = {
    "api_sync_httpx_client": "Sync httpx.Client in api/ (S1)",
    "api_broad_except": "Broad excepts in api/",
    "api_noqa": "# noqa in api/",
    "frontend_eslint_disable": "eslint-disable in frontend/",
    "frontend_ts_suppress": "@ts-ignore/expect-error",
    "android_run_blocking": "runBlocking on Android (S6)",
    "android_suppress": "@Suppress on Android",
    "todo_fixme_hack": "TODO/FIXME/HACK in code",
    "cruft_files": "Tracked cruft files (.old/.backup)",
    "compose_variants": "docker-compose variants",
}


def load_history(history_dir: Path) -> list[dict]:
    snaps = []
    for p in sorted(history_dir.glob("*.json")):
        snaps.append(json.loads(p.read_text(encoding="utf-8")))
    return snaps


def fmt(n) -> str:
    return "—" if n is None else str(n)


def delta(cur, prev) -> str:
    """Direction marker vs the previous snapshot. Lower is better for every
    metric this tool tracks, so ▲ (growth) is the bad direction."""
    if cur is None or prev is None or cur == prev:
        return ""
    return f" {'▲' if cur > prev else '▼'}{abs(cur - prev)}"


def table(rows: list[list[str]]) -> str:
    header, *body = rows
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in body]
    return "\n".join(out)


def metric_rows(snaps: list[dict], label: str, getter) -> list[str]:
    """One table row: label, value per snapshot, delta on the newest."""
    vals = [getter(s) for s in snaps]
    cells = [fmt(v) for v in vals]
    if len(vals) >= 2:
        cells[-1] += delta(vals[-1], vals[-2])
    return [label, *cells]


def render_report(snaps: list[dict]) -> str:
    shown = snaps[-MAX_COLUMNS:]
    dates = [s["generated"] for s in shown]
    latest = shown[-1]
    latest_rep = latest["reports"][-1]

    lines = [
        "# Audit Trend Report",
        "",
        "*Generated by `make audit-metrics` (`tools/audit-metrics/`). Do not edit by hand.*",
        f"*Latest snapshot: **{latest['generated']}** (commit `{latest['commit']}`),"
        f" latest audit: **{latest_rep['month']}**"
        f" ({latest_rep['open_total']} open findings, risk score {latest_rep['risk_score']}).*",
        "",
        "Lower is better for every number on this page;"
        " ▲ marks growth since the previous snapshot, ▼ shrinkage.",
        "",
        "## Risk score",
        "",
        "Weighted open findings of the most recent audit at each snapshot"
        " (CRITICAL=10, HIGH=5, MEDIUM=2, LOW=1).",
        "",
        table([
            ["Metric", *dates],
            metric_rows(shown, "Risk score", lambda s: s["risk_score"]),
            metric_rows(shown, "Open findings", lambda s: s["reports"][-1]["open_total"]),
            *[metric_rows(shown, sev.title(),
                          lambda s, v=sev: s["reports"][-1]["open_by_severity"].get(v))
              for sev in SEVERITIES],
            metric_rows(shown, "Resolved (cumulative)",
                        lambda s: sum(len(r["resolved_ids"]) for r in s["reports"])),
        ]),
        "",
        "## Open findings by category",
        "",
        table([
            ["Category", *dates],
            *[metric_rows(shown, label,
                          lambda s, k=key: s["reports"][-1]["open_by_category"].get(k))
              for key, label in CATEGORY_LABELS.items()],
        ]),
        "",
        "## Hotspot watch (lines)",
        "",
        "Files flagged by the audits as monoliths or hand-synchronized copies."
        " The goal is for these rows to shrink or disappear (— = file deleted).",
        "",
        table([
            ["File", *dates],
            *[metric_rows(shown, f"`{path.rsplit('/', 1)[-1]}`",
                          lambda s, p=path: s["hotspots"].get(p))
              for path in latest["hotspots"]],
        ]),
        "",
        "## Hygiene counters",
        "",
        table([
            ["Counter", *dates],
            *[metric_rows(shown, label,
                          lambda s, k=key: s["hygiene"].get(k))
              for key, label in HYGIENE_LABELS.items()
              if key in latest["hygiene"]],
        ]),
        "",
        "## Test surface",
        "",
        "The one section where growth is good (shown without direction markers).",
        "",
        table([
            ["Metric", *dates],
            *[[f"{area} test files",
               *[fmt(s["areas"].get(area, {}).get("test_files")) for s in shown]]
              for area in ("api", "frontend", "android")],
            ["frontend e2e specs",
             *[fmt(s["areas"].get("frontend_e2e_specs")) for s in shown]],
        ]),
        "",
        "## How to refresh",
        "",
        "```sh",
        "make audit-metrics",
        "```",
        "",
        "Snapshots accumulate under `docs/audits/metrics/history/`;"
        " run it after each `/risk-audit` and let the monthly workflow"
        " (`.github/workflows/audit-metrics.yml`) fill the gaps between audits.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# dashboard
# ---------------------------------------------------------------------------

def svg_line(series: list, width=560, height=120, color="#2563eb") -> str:
    """Tiny inline-SVG line chart; None values break the line."""
    pts = [(i, v) for i, v in enumerate(series) if v is not None]
    if not pts:
        return "<svg></svg>"
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    span_x = max(x1 - x0, 1)
    span_y = max(y1 - y0, 1)
    pad = 8

    def px(x):
        return pad + (x - x0) / span_x * (width - 2 * pad)

    def py(y):
        return height - pad - (y - y0) / span_y * (height - 2 * pad)

    path = " ".join(f"{'M' if i == 0 else 'L'}{px(x):.1f},{py(y):.1f}"
                    for i, (x, y) in enumerate(pts))
    dots = "".join(f'<circle cx="{px(x):.1f}" cy="{py(y):.1f}" r="3" fill="{color}"/>'
                   for x, y in pts)
    return (f'<svg viewBox="0 0 {width} {height}" role="img">'
            f'<path d="{path}" fill="none" stroke="{color}" stroke-width="2"/>'
            f"{dots}</svg>")


def render_dashboard(snaps: list[dict]) -> str:
    dates = [s["generated"] for s in snaps]
    latest = snaps[-1]
    latest_rep = latest["reports"][-1]

    def series(getter):
        return [getter(s) for s in snaps]

    cards = [
        ("Risk score", series(lambda s: s["risk_score"]), "#dc2626"),
        ("Open findings", series(lambda s: s["reports"][-1]["open_total"]), "#ea580c"),
        ("CRITICAL + HIGH open",
         series(lambda s: s["reports"][-1]["open_by_severity"].get("CRITICAL", 0)
                + s["reports"][-1]["open_by_severity"].get("HIGH", 0)), "#b91c1c"),
        ("Hotspot lines (total)",
         series(lambda s: sum(v for v in s["hotspots"].values() if v)), "#2563eb"),
        ("Hygiene counters (total)",
         series(lambda s: sum(s["hygiene"].values())), "#7c3aed"),
        ("Test files (all areas)",
         series(lambda s: sum(s["areas"].get(a, {}).get("test_files", 0)
                              for a in ("api", "frontend", "android"))), "#059669"),
    ]

    tiles = "".join(
        f'<div class="card"><h2>{html.escape(title)}</h2>'
        f'<div class="num">{fmt(vals[-1])}</div>{svg_line(vals, color=color)}'
        f"</div>"
        for title, vals, color in cards
    )

    sev_rows = "".join(
        f"<tr><td>{sev.title()}</td>"
        + "".join(f"<td>{fmt(s['reports'][-1]['open_by_severity'].get(sev))}</td>"
                  for s in snaps)
        + "</tr>"
        for sev in SEVERITIES
    )
    date_heads = "".join(f"<th>{d}</th>" for d in dates)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Audit Trend — Vox Quieta</title>
<style>
  :root {{ color-scheme: light dark; font-family: system-ui, sans-serif; }}
  body {{ margin: 2rem auto; max-width: 72rem; padding: 0 1rem; }}
  h1 {{ margin-bottom: 0.2rem; }}
  .sub {{ color: #6b7280; margin-bottom: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 1rem; }}
  .card {{ border: 1px solid #d1d5db55; border-radius: 10px; padding: 1rem; }}
  .card h2 {{ font-size: 0.9rem; margin: 0 0 0.3rem; color: #6b7280; font-weight: 600; }}
  .card .num {{ font-size: 1.8rem; font-weight: 700; margin-bottom: 0.4rem; }}
  svg {{ width: 100%; height: auto; }}
  table {{ border-collapse: collapse; margin-top: 2rem; width: 100%; }}
  th, td {{ border: 1px solid #d1d5db55; padding: 0.4rem 0.7rem; text-align: right; }}
  th:first-child, td:first-child {{ text-align: left; }}
  .foot {{ margin-top: 2rem; color: #6b7280; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>Audit Trend</h1>
<p class="sub">Latest snapshot {html.escape(latest["generated"])}
 (commit <code>{html.escape(latest["commit"])}</code>) ·
 latest audit <strong>{html.escape(latest_rep["month"])}</strong> ·
 {latest_rep["open_total"]} open findings · risk score {latest_rep["risk_score"]}.
 Lower is better everywhere except tests.</p>
<div class="grid">{tiles}</div>
<table>
<thead><tr><th>Open by severity</th>{date_heads}</tr></thead>
<tbody>{sev_rows}</tbody>
</table>
<p class="foot">Generated by <code>make audit-metrics</code>
 (<code>tools/audit-metrics/</code>). Full tables in
 <a href="./report.md">report.md</a>; audit reports in
 <code>docs/audits/</code>.</p>
</body>
</html>
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=None)
    args = ap.parse_args()

    repo = Path(args.repo_root) if args.repo_root else Path(__file__).resolve().parents[2]
    out_dir = repo / "docs" / "audits" / "metrics"
    snaps = load_history(out_dir / "history")
    if not snaps:
        raise SystemExit("no snapshots — run tools/audit-metrics/analyze.py first")

    (out_dir / "report.md").write_text(render_report(snaps), encoding="utf-8")
    (out_dir / "index.html").write_text(render_dashboard(snaps), encoding="utf-8")
    print(f"wrote {out_dir / 'report.md'} and {out_dir / 'index.html'}")


if __name__ == "__main__":
    main()
