#!/usr/bin/env python3
"""Per-language book-name abbreviation/alias coverage audit (BITB-052).

Loads ``api/utils/translation_registry.py`` directly (bypassing the ``utils``
package ``__init__``, which pulls in DB/HTTP config not needed here) and
reports, for every supported language and each of the 66 canonical books,
which extra recognized forms (abbreviations, singular forms, citation-case
variants) exist beyond the canonical localized name — and which books have
none (a coverage gap).

Regenerate the committed report after any alias/translation-registry change:

    python scripts/audit_book_name_coverage.py

Usage
-----
--output PATH   Where to write the markdown report (default:
                docs/audits/book-name-coverage.md).
--check         Instead of writing a report, verify the case+diacritic fold
                used by normalize_book_name() introduces no cross-book
                collisions across the full alias set. Exits 1 on any
                collision, 0 otherwise. Safe for CI.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
import unicodedata
from pathlib import Path

_REPO_ROOT = Path(__file__).parent.parent
_REGISTRY_PATH = _REPO_ROOT / "api" / "utils" / "translation_registry.py"


def _load_registry():
    """Import translation_registry.py as a standalone module.

    It has zero imports of its own (pure dict literals), so loading it this
    way avoids triggering ``api/utils/__init__.py`` (which imports
    ``config`` and requires ``DATABASE_URL`` to be set) — this script is
    pure static analysis and needs no database or app config.
    """
    spec = importlib.util.spec_from_file_location("translation_registry", _REGISTRY_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fold(text: str) -> str:
    """Same fold as utils.book_names._fold — duplicated here so this script
    has no dependency on the ``utils`` package (see _load_registry)."""
    decomposed = unicodedata.normalize("NFKD", text)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return stripped.lower()


def _build_language_table(reg):
    """Return {language_name: (forward_dict_or_None, [alias_dicts])}."""
    return {
        "English": (None, [reg.ENGLISH_ALIASES]),
        "Italian": (reg.ENGLISH_TO_ITALIAN, [reg.ITALIAN_ALIASES]),
        "German": (reg.ENGLISH_TO_GERMAN, [reg.GERMAN_ALIASES]),
        "Spanish": (reg.ENGLISH_TO_SPANISH, []),
        "French": (reg.ENGLISH_TO_FRENCH, [reg.FRENCH_ALIASES]),
        "Portuguese": (reg.ENGLISH_TO_PORTUGUESE, []),
        "Arabic": (reg.ENGLISH_TO_ARABIC, [reg.ARABIC_CITATION_FORMS]),
        "Russian": (reg.ENGLISH_TO_RUSSIAN, [reg.RUSSIAN_CITATION_FORMS, reg.RUSSIAN_ALIASES]),
        "Chinese": (reg.ENGLISH_TO_CHINESE, [reg.CHINESE_ALIASES]),
        "Korean": (reg.ENGLISH_TO_KOREAN, [reg.KOREAN_ALIASES]),
        "Hindi": (reg.ENGLISH_TO_HINDI, [reg.HINDI_ALIASES]),
    }


def _extra_forms_for_book(
    book: str, canonical: str, alias_dicts: list[dict[str, str]]
) -> list[str]:
    forms = []
    for alias_dict in alias_dicts:
        for alias, english in alias_dict.items():
            if english == book and alias != canonical:
                forms.append(alias)
    return sorted(set(forms))


def generate_report(reg) -> str:
    books = list(reg.ENGLISH_TO_ITALIAN.keys())
    languages = _build_language_table(reg)

    summary_rows = []
    per_language_sections = []

    for language, (forward, alias_dicts) in languages.items():
        with_alias = 0
        gaps = 0
        total_extra = 0
        rows = []
        for book in books:
            canonical = forward.get(book, book) if forward else book
            extra = _extra_forms_for_book(book, book, alias_dicts)
            if extra:
                with_alias += 1
                total_extra += len(extra)
            else:
                gaps += 1
            rows.append((book, canonical, ", ".join(extra) if extra else "— (gap)"))

        summary_rows.append((language, with_alias, gaps, total_extra))

        lines = [
            f"### {language}",
            "",
            "| Book | Canonical form | Recognized aliases/abbreviations |",
            "| --- | --- | --- |",
        ]
        for book, canonical, extra in rows:
            lines.append(f"| {book} | {canonical} | {extra} |")
        per_language_sections.append("\n".join(lines))

    out = [
        "# Book-Name Abbreviation/Alias Coverage Audit (BITB-052)",
        "",
        "Generated by `scripts/audit_book_name_coverage.py` — regenerate after any",
        "change to `api/utils/translation_registry.py` rather than hand-editing this file.",
        "",
        'A "gap" means only the canonical localized form is recognized for that book in',
        "that language — no singular/abbreviation/citation-form variant is registered in",
        "`normalize_book_name`'s alias tables, so an LLM or user producing a shorthand form",
        "in that language for that book will fail to resolve.",
        "",
        "## Summary",
        "",
        "| Language | Books with ≥1 alias | Books canonical-only (gaps) | Total extra forms |",
        "| --- | --- | --- | --- |",
    ]
    for language, with_alias, gaps, total_extra in summary_rows:
        out.append(f"| {language} | {with_alias} | {gaps} | {total_extra} |")
    out.append("")
    out.append("## Per-language detail")
    out.append("")
    out.extend(per_language_sections)
    out.append("")
    return "\n".join(out)


def check_fold_collisions(reg) -> list[str]:
    """Return a list of human-readable collision descriptions (empty = clean)."""
    localized_to_english: dict[str, str] = {}
    languages = _build_language_table(reg)
    for _language, (forward, alias_dicts) in languages.items():
        if forward:
            localized_to_english.update({v: k for k, v in forward.items()})
        for alias_dict in alias_dicts:
            localized_to_english.update(alias_dict)

    folded: dict[str, str] = {_fold(name): name for name in reg.ENGLISH_TO_ITALIAN}
    collisions = []
    for localized, english in localized_to_english.items():
        key = _fold(localized)
        if key in folded and folded[key] != english:
            collisions.append(
                f"{localized!r} -> {key!r} already mapped to {folded[key]!r}, also matches {english!r}"
            )
        else:
            folded.setdefault(key, english)
    return collisions


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "docs" / "audits" / "book-name-coverage.md",
    )
    parser.add_argument(
        "--check", action="store_true", help="Run the fold-collision invariant only"
    )
    args = parser.parse_args()

    reg = _load_registry()

    if args.check:
        collisions = check_fold_collisions(reg)
        if collisions:
            print(f"FAIL: {len(collisions)} diacritic-fold collision(s) found:", file=sys.stderr)
            for c in collisions:
                print(f"  - {c}", file=sys.stderr)
            return 1
        print("OK: no diacritic-fold collisions across all localized/alias book names.")
        return 0

    report = generate_report(reg)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
