"""
Book name localization utilities.

Maps English book names to localized versions for different translations.
Supports: Italian (ita1927), German (schlachter), Spanish (valera),
          French (ls1910), Portuguese (almeida), Arabic (arabicsv).
"""

# Italian book names (Riveduta 1927) - reverse mapping from English
ENGLISH_TO_ITALIAN = {
    "Genesis": "Genesi",
    "Exodus": "Esodo",
    "Leviticus": "Levitico",
    "Numbers": "Numeri",
    "Deuteronomy": "Deuteronomio",
    "Joshua": "Giosuè",
    "Judges": "Giudici",
    "Ruth": "Rut",
    "1 Samuel": "1 Samuele",
    "2 Samuel": "2 Samuele",
    "1 Kings": "1 Re",
    "2 Kings": "2 Re",
    "1 Chronicles": "1 Cronache",
    "2 Chronicles": "2 Cronache",
    "Ezra": "Esdra",
    "Nehemiah": "Nehemia",
    "Esther": "Ester",
    "Job": "Giobbe",
    "Psalms": "Salmi",
    "Proverbs": "Proverbi",
    "Ecclesiastes": "Ecclesiaste",
    "Song of Solomon": "Cantico dei Cantici",
    "Isaiah": "Isaia",
    "Jeremiah": "Geremia",
    "Lamentations": "Lamentazioni",
    "Ezekiel": "Ezechiele",
    "Daniel": "Daniele",
    "Hosea": "Osea",
    "Joel": "Gioele",
    "Amos": "Amos",
    "Obadiah": "Abdia",
    "Jonah": "Giona",
    "Micah": "Michea",
    "Nahum": "Nahum",
    "Habakkuk": "Abacuc",
    "Zephaniah": "Sofonia",
    "Haggai": "Aggeo",
    "Zechariah": "Zaccaria",
    "Malachi": "Malachia",
    "Matthew": "Matteo",
    "Mark": "Marco",
    "Luke": "Luca",
    "John": "Giovanni",
    "Acts": "Atti",
    "Romans": "Romani",
    "1 Corinthians": "1 Corinzi",
    "2 Corinthians": "2 Corinzi",
    "Galatians": "Galati",
    "Ephesians": "Efesini",
    "Philippians": "Filippesi",
    "Colossians": "Colossesi",
    "1 Thessalonians": "1 Tessalonicesi",
    "2 Thessalonians": "2 Tessalonicesi",
    "1 Timothy": "1 Timoteo",
    "2 Timothy": "2 Timoteo",
    "Titus": "Tito",
    "Philemon": "Filemone",
    "Hebrews": "Ebrei",
    "James": "Giacomo",
    "1 Peter": "1 Pietro",
    "2 Peter": "2 Pietro",
    "1 John": "1 Giovanni",
    "2 John": "2 Giovanni",
    "3 John": "3 Giovanni",
    "Jude": "Giuda",
    "Revelation": "Apocalisse",
}

# German book names (Schlachter) - reverse mapping from English
ENGLISH_TO_GERMAN = {
    "Genesis": "1. Mose",
    "Exodus": "2. Mose",
    "Leviticus": "3. Mose",
    "Numbers": "4. Mose",
    "Deuteronomy": "5. Mose",
    "Joshua": "Josua",
    "Judges": "Richter",
    "Ruth": "Ruth",
    "1 Samuel": "1. Samuel",
    "2 Samuel": "2. Samuel",
    "1 Kings": "1. Könige",
    "2 Kings": "2. Könige",
    "1 Chronicles": "1. Chronik",
    "2 Chronicles": "2. Chronik",
    "Ezra": "Esra",
    "Nehemiah": "Nehemia",
    "Esther": "Esther",
    "Job": "Hiob",
    "Psalms": "Psalmen",
    "Proverbs": "Sprüche",
    "Ecclesiastes": "Prediger",
    "Song of Solomon": "Hohelied",
    "Isaiah": "Jesaja",
    "Jeremiah": "Jeremia",
    "Lamentations": "Klagelieder",
    "Ezekiel": "Hesekiel",
    "Daniel": "Daniel",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obadja",
    "Jonah": "Jona",
    "Micah": "Micha",
    "Nahum": "Nahum",
    "Habakkuk": "Habakuk",
    "Zephaniah": "Zephanja",
    "Haggai": "Haggai",
    "Zechariah": "Sacharja",
    "Malachi": "Maleachi",
    "Matthew": "Matthäus",
    "Mark": "Markus",
    "Luke": "Lukas",
    "John": "Johannes",
    "Acts": "Apostelgeschichte",
    "Romans": "Römer",
    "1 Corinthians": "1. Korinther",
    "2 Corinthians": "2. Korinther",
    "Galatians": "Galater",
    "Ephesians": "Epheser",
    "Philippians": "Philipper",
    "Colossians": "Kolosser",
    "1 Thessalonians": "1. Thessalonicher",
    "2 Thessalonians": "2. Thessalonicher",
    "1 Timothy": "1. Timotheus",
    "2 Timothy": "2. Timotheus",
    "Titus": "Titus",
    "Philemon": "Philemon",
    "Hebrews": "Hebräer",
    "James": "Jakobus",
    "1 Peter": "1. Petrus",
    "2 Peter": "2. Petrus",
    "1 John": "1. Johannes",
    "2 John": "2. Johannes",
    "3 John": "3. Johannes",
    "Jude": "Judas",
    "Revelation": "Offenbarung",
}

# Spanish book names (Reina Valera 1909)
ENGLISH_TO_SPANISH = {
    "Genesis": "Génesis",
    "Exodus": "Éxodo",
    "Leviticus": "Levítico",
    "Numbers": "Números",
    "Deuteronomy": "Deuteronomio",
    "Joshua": "Josué",
    "Judges": "Jueces",
    "Ruth": "Rut",
    "1 Samuel": "1 Samuel",
    "2 Samuel": "2 Samuel",
    "1 Kings": "1 Reyes",
    "2 Kings": "2 Reyes",
    "1 Chronicles": "1 Crónicas",
    "2 Chronicles": "2 Crónicas",
    "Ezra": "Esdras",
    "Nehemiah": "Nehemías",
    "Esther": "Ester",
    "Job": "Job",
    "Psalms": "Salmos",
    "Proverbs": "Proverbios",
    "Ecclesiastes": "Eclesiastés",
    "Song of Solomon": "Cantares",
    "Isaiah": "Isaías",
    "Jeremiah": "Jeremías",
    "Lamentations": "Lamentaciones",
    "Ezekiel": "Ezequiel",
    "Daniel": "Daniel",
    "Hosea": "Oseas",
    "Joel": "Joel",
    "Amos": "Amós",
    "Obadiah": "Abdías",
    "Jonah": "Jonás",
    "Micah": "Miqueas",
    "Nahum": "Nahúm",
    "Habakkuk": "Habacuc",
    "Zephaniah": "Sofonías",
    "Haggai": "Hageo",
    "Zechariah": "Zacarías",
    "Malachi": "Malaquías",
    "Matthew": "Mateo",
    "Mark": "Marcos",
    "Luke": "Lucas",
    "John": "Juan",
    "Acts": "Hechos",
    "Romans": "Romanos",
    "1 Corinthians": "1 Corintios",
    "2 Corinthians": "2 Corintios",
    "Galatians": "Gálatas",
    "Ephesians": "Efesios",
    "Philippians": "Filipenses",
    "Colossians": "Colosenses",
    "1 Thessalonians": "1 Tesalonicenses",
    "2 Thessalonians": "2 Tesalonicenses",
    "1 Timothy": "1 Timoteo",
    "2 Timothy": "2 Timoteo",
    "Titus": "Tito",
    "Philemon": "Filemón",
    "Hebrews": "Hebreos",
    "James": "Santiago",
    "1 Peter": "1 Pedro",
    "2 Peter": "2 Pedro",
    "1 John": "1 Juan",
    "2 John": "2 Juan",
    "3 John": "3 Juan",
    "Jude": "Judas",
    "Revelation": "Apocalipsis",
}

# French book names (Louis Segond 1910)
ENGLISH_TO_FRENCH = {
    "Genesis": "Genèse",
    "Exodus": "Exode",
    "Leviticus": "Lévitique",
    "Numbers": "Nombres",
    "Deuteronomy": "Deutéronome",
    "Joshua": "Josué",
    "Judges": "Juges",
    "Ruth": "Ruth",
    "1 Samuel": "1 Samuel",
    "2 Samuel": "2 Samuel",
    "1 Kings": "1 Rois",
    "2 Kings": "2 Rois",
    "1 Chronicles": "1 Chroniques",
    "2 Chronicles": "2 Chroniques",
    "Ezra": "Esdras",
    "Nehemiah": "Néhémie",
    "Esther": "Esther",
    "Job": "Job",
    "Psalms": "Psaumes",
    "Proverbs": "Proverbes",
    "Ecclesiastes": "Ecclésiaste",
    "Song of Solomon": "Cantique des Cantiques",
    "Isaiah": "Ésaïe",
    "Jeremiah": "Jérémie",
    "Lamentations": "Lamentations",
    "Ezekiel": "Ézéchiel",
    "Daniel": "Daniel",
    "Hosea": "Osée",
    "Joel": "Joël",
    "Amos": "Amos",
    "Obadiah": "Abdias",
    "Jonah": "Jonas",
    "Micah": "Michée",
    "Nahum": "Nahum",
    "Habakkuk": "Habacuc",
    "Zephaniah": "Sophonie",
    "Haggai": "Aggée",
    "Zechariah": "Zacharie",
    "Malachi": "Malachie",
    "Matthew": "Matthieu",
    "Mark": "Marc",
    "Luke": "Luc",
    "John": "Jean",
    "Acts": "Actes des Apôtres",
    "Romans": "Romains",
    "1 Corinthians": "1 Corinthiens",
    "2 Corinthians": "2 Corinthiens",
    "Galatians": "Galates",
    "Ephesians": "Éphésiens",
    "Philippians": "Philippiens",
    "Colossians": "Colossiens",
    "1 Thessalonians": "1 Thessaloniciens",
    "2 Thessalonians": "2 Thessaloniciens",
    "1 Timothy": "1 Timothée",
    "2 Timothy": "2 Timothée",
    "Titus": "Tite",
    "Philemon": "Philémon",
    "Hebrews": "Hébreux",
    "James": "Jacques",
    "1 Peter": "1 Pierre",
    "2 Peter": "2 Pierre",
    "1 John": "1 Jean",
    "2 John": "2 Jean",
    "3 John": "3 Jean",
    "Jude": "Jude",
    "Revelation": "Apocalypse",
}

# Portuguese book names (Almeida Atualizada)
ENGLISH_TO_PORTUGUESE = {
    "Genesis": "Gênesis",
    "Exodus": "Êxodo",
    "Leviticus": "Levítico",
    "Numbers": "Números",
    "Deuteronomy": "Deuteronômio",
    "Joshua": "Josué",
    "Judges": "Juízes",
    "Ruth": "Rute",
    "1 Samuel": "1 Samuel",
    "2 Samuel": "2 Samuel",
    "1 Kings": "1 Reis",
    "2 Kings": "2 Reis",
    "1 Chronicles": "1 Crônicas",
    "2 Chronicles": "2 Crônicas",
    "Ezra": "Esdras",
    "Nehemiah": "Neemias",
    "Esther": "Ester",
    "Job": "Jó",
    "Psalms": "Salmos",
    "Proverbs": "Provérbios",
    "Ecclesiastes": "Eclesiastes",
    "Song of Solomon": "Cântico dos Cânticos",
    "Isaiah": "Isaías",
    "Jeremiah": "Jeremias",
    "Lamentations": "Lamentações",
    "Ezekiel": "Ezequiel",
    "Daniel": "Daniel",
    "Hosea": "Oseias",
    "Joel": "Joel",
    "Amos": "Amós",
    "Obadiah": "Obadias",
    "Jonah": "Jonas",
    "Micah": "Miquéias",
    "Nahum": "Naum",
    "Habakkuk": "Habacuque",
    "Zephaniah": "Sofonias",
    "Haggai": "Ageu",
    "Zechariah": "Zacarias",
    "Malachi": "Malaquias",
    "Matthew": "Mateus",
    "Mark": "Marcos",
    "Luke": "Lucas",
    "John": "João",
    "Acts": "Atos",
    "Romans": "Romanos",
    "1 Corinthians": "1 Coríntios",
    "2 Corinthians": "2 Coríntios",
    "Galatians": "Gálatas",
    "Ephesians": "Efésios",
    "Philippians": "Filipenses",
    "Colossians": "Colossenses",
    "1 Thessalonians": "1 Tessalonicenses",
    "2 Thessalonians": "2 Tessalonicenses",
    "1 Timothy": "1 Timóteo",
    "2 Timothy": "2 Timóteo",
    "Titus": "Tito",
    "Philemon": "Filemom",
    "Hebrews": "Hebreus",
    "James": "Tiago",
    "1 Peter": "1 Pedro",
    "2 Peter": "2 Pedro",
    "1 John": "1 João",
    "2 John": "2 João",
    "3 John": "3 João",
    "Jude": "Judas",
    "Revelation": "Apocalipse",
}

# Arabic book names (Smith & Van Dyke)
ENGLISH_TO_ARABIC = {
    "Genesis": "تكوين",
    "Exodus": "خروج",
    "Leviticus": "لاويين",
    "Numbers": "عدد",
    "Deuteronomy": "تثنية",
    "Joshua": "يشوع",
    "Judges": "القضاة",
    "Ruth": "راعوث",
    "1 Samuel": "1 صموئيل",
    "2 Samuel": "2 صموئيل",
    "1 Kings": "1 الملوك",
    "2 Kings": "2 الملوك",
    "1 Chronicles": "1 أخبار الأيام",
    "2 Chronicles": "2 أخبار الأيام",
    "Ezra": "عزرا",
    "Nehemiah": "نحميا",
    "Esther": "أستير",
    "Job": "أيوب",
    "Psalms": "المزامير",
    "Proverbs": "الأمثال",
    "Ecclesiastes": "الجامعة",
    "Song of Solomon": "نشيد الأنشاد",
    "Isaiah": "إشعياء",
    "Jeremiah": "إرميا",
    "Lamentations": "مراثي إرميا",
    "Ezekiel": "حزقيال",
    "Daniel": "دانيال",
    "Hosea": "هوشع",
    "Joel": "يوئيل",
    "Amos": "عاموس",
    "Obadiah": "عوبديا",
    "Jonah": "يونان",
    "Micah": "ميخا",
    "Nahum": "ناحوم",
    "Habakkuk": "حبقوق",
    "Zephaniah": "صفنيا",
    "Haggai": "حجي",
    "Zechariah": "زكريا",
    "Malachi": "ملاخي",
    "Matthew": "متى",
    "Mark": "مرقس",
    "Luke": "لوقا",
    "John": "يوحنا",
    "Acts": "أعمال الرسل",
    "Romans": "رومية",
    "1 Corinthians": "1 كورنثوس",
    "2 Corinthians": "2 كورنثوس",
    "Galatians": "غلاطية",
    "Ephesians": "أفسس",
    "Philippians": "فيليبي",
    "Colossians": "كولوسي",
    "1 Thessalonians": "1 تسالونيكي",
    "2 Thessalonians": "2 تسالونيكي",
    "1 Timothy": "1 تيموثاوس",
    "2 Timothy": "2 تيموثاوس",
    "Titus": "تيطس",
    "Philemon": "فليمون",
    "Hebrews": "عبرانيين",
    "James": "يعقوب",
    "1 Peter": "1 بطرس",
    "2 Peter": "2 بطرس",
    "1 John": "1 يوحنا",
    "2 John": "2 يوحنا",
    "3 John": "3 يوحنا",
    "Jude": "يهوذا",
    "Revelation": "الرؤيا",
}

# Mapping of translation codes to their book name mappings
TRANSLATION_BOOK_NAMES = {
    "ita1927": ENGLISH_TO_ITALIAN,
    "schlachter": ENGLISH_TO_GERMAN,
    "valera": ENGLISH_TO_SPANISH,
    "ls1910": ENGLISH_TO_FRENCH,
    "almeida": ENGLISH_TO_PORTUGUESE,
    "arabicsv": ENGLISH_TO_ARABIC,
    # English translations don't need mapping
    "kjv": None,
    "web": None,
}

# Reverse mappings (localized -> English)
ITALIAN_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_ITALIAN.items()}
GERMAN_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_GERMAN.items()}
SPANISH_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_SPANISH.items()}
FRENCH_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_FRENCH.items()}
PORTUGUESE_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_PORTUGUESE.items()}
ARABIC_TO_ENGLISH = {v: k for k, v in ENGLISH_TO_ARABIC.items()}

# Combined reverse mapping for all languages
LOCALIZED_TO_ENGLISH = {
    **ITALIAN_TO_ENGLISH,
    **GERMAN_TO_ENGLISH,
    **SPANISH_TO_ENGLISH,
    **FRENCH_TO_ENGLISH,
    **PORTUGUESE_TO_ENGLISH,
    **ARABIC_TO_ENGLISH,
}


def get_localized_book_name(english_name: str, translation_code: str | None) -> str:
    """
    Get the localized book name for a given English book name.

    Args:
        english_name: Standard English book name (e.g., "Genesis", "Psalms")
        translation_code: Translation code (e.g., "ita1927", "schlachter")

    Returns:
        Localized book name (e.g., "Genesi", "Psalmen") or English name if no mapping
    """
    if translation_code is None:
        return english_name

    book_names = TRANSLATION_BOOK_NAMES.get(translation_code)

    if book_names is None:
        # English translations use standard names
        return english_name

    return book_names.get(english_name, english_name)


def normalize_book_name(book_name: str) -> str:
    """
    Convert a localized book name to standard English.

    Handles book names in any supported language (Italian, German, Spanish,
    French, Portuguese, Arabic, English).

    Args:
        book_name: Book name in any language (e.g., "Giovanni", "Jean", "Juan", "John")

    Returns:
        Standard English book name (e.g., "John")
    """
    # First check if it's already English (exists as a key in any mapping)
    if book_name in ENGLISH_TO_ITALIAN:
        return book_name

    # Try to find in reverse mappings
    return LOCALIZED_TO_ENGLISH.get(book_name, book_name)
