"""
Topic Detection for Scripture Search Boosting.

Maps common keywords/phrases to biblical topic names for fast,
keyword-based topic detection. No LLM or NLP required.
"""

import time

from utils.logging_config import get_logger

logger = get_logger(__name__)

# Maps topic names to lists of keywords/phrases across 7 languages
# EN, IT, DE, ES, FR, PT, AR
TOPIC_KEYWORD_MAP: dict[str, list[str]] = {
    "anxiety": [
        # EN
        "anxious",
        "anxiety",
        "worried",
        "worry",
        "worrying",
        "stress",
        "stressed",
        "nervous",
        "panic",
        "overwhelmed",
        "dread",
        "apprehensive",
        "uneasy",
        # IT
        "ansioso",
        "ansia",
        "preoccupato",
        "preoccupazione",
        "stressato",
        "stress",
        "nervoso",
        "panico",
        "sopraffatto",
        # DE
        "ängstlich",
        "angst",
        "besorgt",
        "sorge",
        "gestresst",
        "stress",
        "nervös",
        "panik",
        "überwältigt",
        # ES
        "ansioso",
        "ansiedad",
        "preocupado",
        "preocupación",
        "estresado",
        "estrés",
        "nervioso",
        "pánico",
        "agobiado",
        # FR
        "anxieux",
        "anxiété",
        "inquiet",
        "inquiétude",
        "stressé",
        "stress",
        "nerveux",
        "panique",
        "accablé",
        # PT
        "ansioso",
        "ansiedade",
        "preocupado",
        "preocupação",
        "estressado",
        "estresse",
        "nervoso",
        "pânico",
        "sobrecarregado",
        # AR
        "قلق",
        "توتر",
        "مضطرب",
        "خوف",
    ],
    "peace": [
        # EN
        "peace",
        "peaceful",
        "calm",
        "calm down",
        "quiet",
        "rest",
        "serenity",
        "tranquil",
        "tranquility",
        "stillness",
        "composed",
        "serene",
        # IT
        "pace",
        "pacifico",
        "calma",
        "calmo",
        "quiete",
        "riposo",
        "serenità",
        "tranquillo",
        "tranquillità",
        # DE
        "frieden",
        "friedlich",
        "ruhe",
        "ruhig",
        "stille",
        "gelassenheit",
        "besonnen",
        "besinnlich",
        # ES
        "paz",
        "tranquilo",
        "calma",
        "quietud",
        "descanso",
        "serenidad",
        "sosiego",
        "apacible",
        # FR
        "paix",
        "paisible",
        "calme",
        "tranquille",
        "repos",
        "sérénité",
        "quiétude",
        "serein",
        # PT
        "paz",
        "pacífico",
        "calma",
        "calmo",
        "quietude",
        "repouso",
        "serenidade",
        "tranquilo",
        "tranquilidade",
        # AR
        "سلام",
        "هدوء",
        "طمأنينة",
        "راحة",
    ],
    "forgiveness": [
        # EN
        "forgive",
        "forgiveness",
        "forgiving",
        "forgiven",
        "mercy",
        "pardon",
        "reconcile",
        "reconciliation",
        "let go",
        "holding grudge",
        "resentment",
        "bitterness",
        "grudge",
        # IT
        "perdonare",
        "perdono",
        "misericordia",
        "grazia",
        "riconciliazione",
        "risentimento",
        "amarezza",
        "rancore",
        # DE
        "vergeben",
        "vergebung",
        "barmherzigkeit",
        "gnade",
        "versöhnung",
        "groll",
        "verbitterung",
        "nachtragen",
        # ES
        "perdonar",
        "perdón",
        "misericordia",
        "gracia",
        "reconciliación",
        "rencor",
        "amargura",
        "resentimiento",
        # FR
        "pardonner",
        "pardon",
        "miséricorde",
        "grâce",
        "réconciliation",
        "rancœur",
        "amertume",
        "ressentiment",
        # PT
        "perdoar",
        "perdão",
        "misericórdia",
        "graça",
        "reconciliação",
        "rancor",
        "amargura",
        "ressentimento",
        # AR
        "مغفرة",
        "عفو",
        "رحمة",
        "مصالحة",
    ],
    "anger": [
        # EN
        "angry",
        "anger",
        "mad",
        "furious",
        "rage",
        "frustrated",
        "frustration",
        "irritated",
        "irritation",
        "annoyed",
        "wrath",
        "hostile",
        "hostility",
        # IT
        "arrabbiato",
        "rabbia",
        "furioso",
        "furia",
        "frustrato",
        "frustrazione",
        "irritato",
        "ira",
        "collera",
        "ostile",
        # DE
        "wütend",
        "zorn",
        "wut",
        "ärger",
        "frustriert",
        "frustration",
        "gereizt",
        "feindseligkeit",
        "aggressiv",
        # ES
        "enojado",
        "ira",
        "enfurecido",
        "furia",
        "frustrado",
        "frustración",
        "irritado",
        "cólera",
        "hostil",
        # FR
        "en colère",
        "colère",
        "furieux",
        "fureur",
        "frustré",
        "frustration",
        "irrité",
        "irritation",
        "courroux",
        "hostile",
        # PT
        "com raiva",
        "raiva",
        "furioso",
        "fúria",
        "frustrado",
        "frustração",
        "irritado",
        "cólera",
        "hostil",
        # AR
        "غضب",
        "غاضب",
        "محبط",
        "إحباط",
    ],
    "loneliness": [
        # EN
        "alone",
        "lonely",
        "loneliness",
        "isolated",
        "isolation",
        "abandoned",
        "unloved",
        "unwanted",
        "rejected",
        "rejection",
        "friendless",
        "solitary",
        # IT
        "solo",
        "solitudine",
        "isolato",
        "isolamento",
        "abbandonato",
        "non amato",
        "rifiutato",
        "senza amici",
        # DE
        "allein",
        "einsamkeit",
        "einsam",
        "isoliert",
        "isolation",
        "verlassen",
        "ungeliebt",
        "abgelehnt",
        "ohne freunde",
        # ES
        "solo",
        "soledad",
        "aislado",
        "aislamiento",
        "abandonado",
        "no querido",
        "rechazado",
        "sin amigos",
        # FR
        "seul",
        "solitude",
        "solitaire",
        "isolé",
        "isolement",
        "abandonné",
        "mal aimé",
        "rejeté",
        "sans amis",
        # PT
        "sozinho",
        "solidão",
        "solitário",
        "isolado",
        "isolamento",
        "abandonado",
        "não amado",
        "rejeitado",
        "sem amigos",
        # AR
        "وحيد",
        "عزلة",
        "مهجور",
        "منبوذ",
    ],
    "trust": [
        # EN
        "trust",
        "faith",
        "believe",
        "belief",
        "confidence",
        "rely",
        "relying",
        "depend",
        "surrender",
        "let go and let god",
        "trust god",
        # IT
        "fiducia",
        "fede",
        "credere",
        "convinzione",
        "affidarsi",
        "confidare",
        "abbandonarsi",
        "fidarsi",
        # DE
        "vertrauen",
        "glaube",
        "glauben",
        "zuversicht",
        "sich verlassen",
        "hingabe",
        "gottvertrauen",
        # ES
        "confianza",
        "fe",
        "creer",
        "creencia",
        "confiar en dios",
        "depender",
        "entregarse",
        # FR
        "confiance",
        "foi",
        "croire",
        "croyance",
        "se confier",
        "se fier",
        "s'abandonner",
        "faire confiance",
        # PT
        "confiança",
        "fé",
        "acreditar",
        "crença",
        "confiar em deus",
        "depender",
        "entregar-se",
        # AR
        "ثقة",
        "إيمان",
        "توكل",
        "توكل على الله",
    ],
    "fear": [
        # EN
        "fear",
        "afraid",
        "scared",
        "frightened",
        "terror",
        "terrified",
        "phobia",
        "dread",
        "fearful",
        "timid",
        "cowardly",
        "courage",
        # IT
        "paura",
        "spaventato",
        "spavento",
        "terrore",
        "terrorizzato",
        "fobia",
        "pauroso",
        "vigliacco",
        "coraggio",
        # DE
        "angst",
        "furcht",
        "fürchten",
        "erschrocken",
        "schrecken",
        "terror",
        "phobie",
        "ängstlich",
        "mut",
        "feige",
        # ES
        "miedo",
        "asustado",
        "susto",
        "terror",
        "aterrorizado",
        "fobia",
        "temeroso",
        "cobarde",
        "valentía",
        # FR
        "peur",
        "effrayé",
        "frayeur",
        "terreur",
        "terrorisé",
        "phobie",
        "craintif",
        "couard",
        "courage",
        # PT
        "medo",
        "assustado",
        "susto",
        "terror",
        "aterrorizado",
        "fobia",
        "medroso",
        "covarde",
        "coragem",
        # AR
        "خوف",
        "مخيف",
        "رعب",
        "فزع",
    ],
    "hope": [
        # EN
        "hope",
        "hopeful",
        "hopeless",
        "despair",
        "desperate",
        "discouraged",
        "future",
        "promise",
        "expectation",
        "optimism",
        # IT
        "speranza",
        "speranzoso",
        "disperato",
        "disperazione",
        "scoraggiato",
        "futuro",
        "promessa",
        "aspettativa",
        "ottimismo",
        # DE
        "hoffnung",
        "hoffnungsvoll",
        "hoffnungslos",
        "verzweiflung",
        "verzweifelt",
        "entmutigt",
        "zukunft",
        "versprechen",
        "optimismus",
        # ES
        "esperanza",
        "esperanzado",
        "desesperado",
        "desesperación",
        "desanimado",
        "futuro",
        "promesa",
        "expectativa",
        "optimismo",
        # FR
        "espoir",
        "espérance",
        "plein d'espoir",
        "désespéré",
        "désespoir",
        "découragé",
        "futur",
        "promesse",
        "optimisme",
        # PT
        "esperança",
        "esperançoso",
        "desesperado",
        "desespero",
        "desanimado",
        "futuro",
        "promessa",
        "expectativa",
        "otimismo",
        # AR
        "أمل",
        "يأس",
        "مستقبل",
        "وعد",
    ],
    "love": [
        # EN
        "love",
        "loved",
        "unloved",
        "compassion",
        "kindness",
        "care",
        "relationship",
        "beloved",
        "cherish",
        "adore",
        # IT
        "amore",
        "amato",
        "compassione",
        "gentilezza",
        "cura",
        "relazione",
        "amato",
        "adorare",
        # DE
        "liebe",
        "geliebt",
        "mitgefühl",
        "güte",
        "fürsorge",
        "beziehung",
        "geliebte",
        "verehren",
        # ES
        "amor",
        "amado",
        "compasión",
        "bondad",
        "cuidado",
        "relación",
        "adorar",
        # FR
        "amour",
        "aimé",
        "compassion",
        "bonté",
        "soin",
        "relation",
        "chéri",
        "adorer",
        # PT
        "amor",
        "amado",
        "compaixão",
        "bondade",
        "cuidado",
        "relacionamento",
        "adorar",
        # AR
        "حب",
        "محبة",
        "رحمة",
        "عطف",
    ],
    "grief": [
        # EN
        "grief",
        "grieve",
        "grieving",
        "mourning",
        "mourn",
        "loss",
        "lost",
        "sorrow",
        "sad",
        "sadness",
        "depression",
        "depressed",
        "heartbroken",
        # IT
        "dolore",
        "lutto",
        "perdita",
        "tristezza",
        "triste",
        "depressione",
        "depresso",
        "cuore spezzato",
        "piangere",
        # DE
        "trauer",
        "trauern",
        "verlust",
        "traurigkeit",
        "traurig",
        "depression",
        "deprimiert",
        "herzschmerz",
        "betrauern",
        # ES
        "dolor",
        "duelo",
        "pérdida",
        "tristeza",
        "triste",
        "depresión",
        "deprimido",
        "corazón roto",
        "llorar",
        # FR
        "deuil",
        "douleur",
        "perte",
        "tristesse",
        "triste",
        "dépression",
        "déprimé",
        "cœur brisé",
        "pleurer",
        # PT
        "luto",
        "dor",
        "perda",
        "tristeza",
        "triste",
        "depressão",
        "deprimido",
        "coração partido",
        "chorar",
        # AR
        "حزن",
        "حداد",
        "خسارة",
        "فقدان",
    ],
    "guidance": [
        # EN
        "guidance",
        "guide",
        "direction",
        "lost",
        "confused",
        "decision",
        "wisdom",
        "path",
        "way",
        "purpose",
        "calling",
        "discernment",
        # IT
        "guida",
        "direzione",
        "perso",
        "confuso",
        "decisione",
        "saggezza",
        "cammino",
        "scopo",
        "discernimento",
        # DE
        "führung",
        "leitung",
        "richtung",
        "verloren",
        "verwirrt",
        "entscheidung",
        "weisheit",
        "weg",
        "zweck",
        "berufung",
        # ES
        "guía",
        "dirección",
        "perdido",
        "confundido",
        "decisión",
        "sabiduría",
        "camino",
        "propósito",
        "discernimiento",
        # FR
        "guide",
        "direction",
        "perdu",
        "confus",
        "décision",
        "sagesse",
        "chemin",
        "but",
        "discernement",
        # PT
        "guia",
        "direção",
        "perdido",
        "confuso",
        "decisão",
        "sabedoria",
        "caminho",
        "propósito",
        "discernimento",
        # AR
        "هداية",
        "إرشاد",
        "ضائع",
        "قرار",
        "حكمة",
    ],
    "patience": [
        # EN
        "patience",
        "patient",
        "impatient",
        "waiting",
        "wait",
        "endure",
        "endurance",
        "persevere",
        "perseverance",
        "long-suffering",
        # IT
        "pazienza",
        "paziente",
        "impaziente",
        "aspettare",
        "aspettativa",
        "sopportare",
        "sopportazione",
        "perseverare",
        "perseveranza",
        # DE
        "geduld",
        "geduldig",
        "ungeduldig",
        "warten",
        "ausdauer",
        "ertragen",
        "durchhalten",
        "beharrlichkeit",
        # ES
        "paciencia",
        "paciente",
        "impaciente",
        "esperar",
        "espera",
        "soportar",
        "perseverar",
        "perseverancia",
        # FR
        "patience",
        "patient",
        "impatient",
        "attendre",
        "attente",
        "endurer",
        "persévérer",
        "persévérance",
        # PT
        "paciência",
        "paciente",
        "impaciente",
        "esperar",
        "espera",
        "suportar",
        "perseverar",
        "perseverança",
        # AR
        "صبر",
        "صابر",
        "انتظار",
        "تحمل",
    ],
    "joy": [
        # EN
        "joy",
        "joyful",
        "happy",
        "happiness",
        "gladness",
        "rejoice",
        "delight",
        "cheerful",
        "blessed",
        "blessings",
        # IT
        "gioia",
        "gioioso",
        "felice",
        "felicità",
        "letizia",
        "rallegrarsi",
        "delizia",
        "allegro",
        "benedetto",
        "benedizioni",
        # DE
        "freude",
        "fröhlich",
        "glücklich",
        "glück",
        "frohlocken",
        "entzücken",
        "heiter",
        "gesegnet",
        "segnungen",
        # ES
        "alegría",
        "gozoso",
        "feliz",
        "felicidad",
        "regocijarse",
        "deleite",
        "animado",
        "bendecido",
        "bendiciones",
        # FR
        "joie",
        "joyeux",
        "heureux",
        "bonheur",
        "se réjouir",
        "délice",
        "gai",
        "béni",
        "bénédictions",
        # PT
        "alegria",
        "alegre",
        "feliz",
        "felicidade",
        "rejubilar",
        "prazer",
        "animado",
        "abençoado",
        "bênçãos",
        # AR
        "فرح",
        "سعادة",
        "بهجة",
        "مباركة",
    ],
}


def detect_topics(message: str) -> list[str]:
    """
    Detect biblical topics in user message using keyword matching.

    Fast O(n*k) keyword scan — no LLM or NLP required.
    Typical runtime: <1ms for normal messages.

    Args:
        message: User's message text

    Returns:
        List of detected topic names (may be empty)
    """
    start_time = time.monotonic()
    message_lower = message.lower()
    detected: list[str] = []

    for topic, keywords in TOPIC_KEYWORD_MAP.items():
        if any(keyword in message_lower for keyword in keywords):
            detected.append(topic)

    elapsed_ms = (time.monotonic() - start_time) * 1000
    logger.debug(
        "Topic detection completed",
        extra={
            "message_length": len(message),
            "detected_topics": detected,
            "elapsed_ms": round(elapsed_ms, 2),
        },
    )

    return detected
