"""
Topic Detection for Scripture Search Boosting.

Maps common keywords/phrases to biblical topic names for fast,
keyword-based topic detection. No LLM or NLP required.
"""

import time

from utils.logging_config import get_logger

logger = get_logger(__name__)

TOPIC_KEYWORDS_BY_LANGUAGE: dict[str, dict[str, list[str]]] = {
    "anxiety": {
        "en": [
            "anxious",
            "anxiety",
            "worried",
            "worry",
            "worrying",
            "stress",
            "stressed",
            "nervous",
            "panic",
            "overwhelmed",
            "dread",
            "apprehensive",
            "uneasy",
        ],
        "it": [
            "ansioso",
            "ansia",
            "preoccupato",
            "preoccupazione",
            "stressato",
            "stress",
            "nervoso",
            "panico",
            "sopraffatto",
        ],
        "de": [
            "ängstlich",
            "angst",
            "besorgt",
            "sorge",
            "gestresst",
            "stress",
            "nervös",
            "panik",
            "überwältigt",
        ],
        "es": [
            "ansioso",
            "ansiedad",
            "preocupado",
            "preocupación",
            "estresado",
            "estrés",
            "nervioso",
            "pánico",
            "agobiado",
        ],
        "fr": [
            "anxieux",
            "anxiété",
            "inquiet",
            "inquiétude",
            "stressé",
            "stress",
            "nerveux",
            "panique",
            "accablé",
        ],
        "pt": [
            "ansioso",
            "ansiedade",
            "preocupado",
            "preocupação",
            "estressado",
            "estresse",
            "nervoso",
            "pânico",
            "sobrecarregado",
        ],
        "ar": [
            "قلق",
            "توتر",
            "مضطرب",
            "خوف",
        ],
    },
    "peace": {
        "en": [
            "peace",
            "peaceful",
            "calm",
            "calm down",
            "quiet",
            "rest",
            "serenity",
            "tranquil",
            "tranquility",
            "stillness",
            "composed",
            "serene",
        ],
        "it": [
            "pace",
            "pacifico",
            "calma",
            "calmo",
            "quiete",
            "riposo",
            "serenità",
            "tranquillo",
            "tranquillità",
        ],
        "de": [
            "frieden",
            "friedlich",
            "ruhe",
            "ruhig",
            "stille",
            "gelassenheit",
            "besonnen",
            "besinnlich",
        ],
        "es": [
            "paz",
            "tranquilo",
            "calma",
            "quietud",
            "descanso",
            "serenidad",
            "sosiego",
            "apacible",
        ],
        "fr": [
            "paix",
            "paisible",
            "calme",
            "tranquille",
            "repos",
            "sérénité",
            "quiétude",
            "serein",
        ],
        "pt": [
            "paz",
            "pacífico",
            "calma",
            "calmo",
            "quietude",
            "repouso",
            "serenidade",
            "tranquilo",
            "tranquilidade",
        ],
        "ar": [
            "سلام",
            "هدوء",
            "طمأنينة",
            "راحة",
        ],
    },
    "forgiveness": {
        "en": [
            "forgive",
            "forgiveness",
            "forgiving",
            "forgiven",
            "mercy",
            "pardon",
            "reconcile",
            "reconciliation",
            "let go",
            "holding grudge",
            "resentment",
            "bitterness",
            "grudge",
        ],
        "it": [
            "perdonare",
            "perdono",
            "misericordia",
            "grazia",
            "riconciliazione",
            "risentimento",
            "amarezza",
            "rancore",
        ],
        "de": [
            "vergeben",
            "vergebung",
            "barmherzigkeit",
            "gnade",
            "versöhnung",
            "groll",
            "verbitterung",
            "nachtragen",
        ],
        "es": [
            "perdonar",
            "perdón",
            "misericordia",
            "gracia",
            "reconciliación",
            "rencor",
            "amargura",
            "resentimiento",
        ],
        "fr": [
            "pardonner",
            "pardon",
            "miséricorde",
            "grâce",
            "réconciliation",
            "rancœur",
            "amertume",
            "ressentiment",
        ],
        "pt": [
            "perdoar",
            "perdão",
            "misericórdia",
            "graça",
            "reconciliação",
            "rancor",
            "amargura",
            "ressentimento",
        ],
        "ar": [
            "مغفرة",
            "عفو",
            "رحمة",
            "مصالحة",
        ],
    },
    "anger": {
        "en": [
            "angry",
            "anger",
            "mad",
            "furious",
            "rage",
            "frustrated",
            "frustration",
            "irritated",
            "irritation",
            "annoyed",
            "wrath",
            "hostile",
            "hostility",
        ],
        "it": [
            "arrabbiato",
            "rabbia",
            "furioso",
            "furia",
            "frustrato",
            "frustrazione",
            "irritato",
            "ira",
            "collera",
            "ostile",
        ],
        "de": [
            "wütend",
            "zorn",
            "wut",
            "ärger",
            "frustriert",
            "frustration",
            "gereizt",
            "feindseligkeit",
            "aggressiv",
        ],
        "es": [
            "enojado",
            "ira",
            "enfurecido",
            "furia",
            "frustrado",
            "frustración",
            "irritado",
            "cólera",
            "hostil",
        ],
        "fr": [
            "en colère",
            "colère",
            "furieux",
            "fureur",
            "frustré",
            "frustration",
            "irrité",
            "irritation",
            "courroux",
            "hostile",
        ],
        "pt": [
            "com raiva",
            "raiva",
            "furioso",
            "fúria",
            "frustrado",
            "frustração",
            "irritado",
            "cólera",
            "hostil",
        ],
        "ar": [
            "غضب",
            "غاضب",
            "محبط",
            "إحباط",
        ],
    },
    "loneliness": {
        "en": [
            "alone",
            "lonely",
            "loneliness",
            "isolated",
            "isolation",
            "abandoned",
            "unloved",
            "unwanted",
            "rejected",
            "rejection",
            "friendless",
            "solitary",
        ],
        "it": [
            "solo",
            "solitudine",
            "isolato",
            "isolamento",
            "abbandonato",
            "non amato",
            "rifiutato",
            "senza amici",
        ],
        "de": [
            "allein",
            "einsamkeit",
            "einsam",
            "isoliert",
            "isolation",
            "verlassen",
            "ungeliebt",
            "abgelehnt",
            "ohne freunde",
        ],
        "es": [
            "solo",
            "soledad",
            "aislado",
            "aislamiento",
            "abandonado",
            "no querido",
            "rechazado",
            "sin amigos",
        ],
        "fr": [
            "seul",
            "solitude",
            "solitaire",
            "isolé",
            "isolement",
            "abandonné",
            "mal aimé",
            "rejeté",
            "sans amis",
        ],
        "pt": [
            "sozinho",
            "solidão",
            "solitário",
            "isolado",
            "isolamento",
            "abandonado",
            "não amado",
            "rejeitado",
            "sem amigos",
        ],
        "ar": [
            "وحيد",
            "عزلة",
            "مهجور",
            "منبوذ",
        ],
    },
    "trust": {
        "en": [
            "trust",
            "faith",
            "believe",
            "belief",
            "confidence",
            "rely",
            "relying",
            "depend",
            "surrender",
            "let go and let god",
            "trust god",
        ],
        "it": [
            "fiducia",
            "fede",
            "credere",
            "convinzione",
            "affidarsi",
            "confidare",
            "abbandonarsi",
            "fidarsi",
        ],
        "de": [
            "vertrauen",
            "glaube",
            "glauben",
            "zuversicht",
            "sich verlassen",
            "hingabe",
            "gottvertrauen",
        ],
        "es": [
            "confianza",
            "fe",
            "creer",
            "creencia",
            "confiar en dios",
            "depender",
            "entregarse",
        ],
        "fr": [
            "confiance",
            "foi",
            "croire",
            "croyance",
            "se confier",
            "se fier",
            "s'abandonner",
            "faire confiance",
        ],
        "pt": [
            "confiança",
            "fé",
            "acreditar",
            "crença",
            "confiar em deus",
            "depender",
            "entregar-se",
        ],
        "ar": [
            "ثقة",
            "إيمان",
            "توكل",
            "توكل على الله",
        ],
    },
    "fear": {
        "en": [
            "fear",
            "afraid",
            "scared",
            "frightened",
            "terror",
            "terrified",
            "phobia",
            "dread",
            "fearful",
            "timid",
            "cowardly",
            "courage",
        ],
        "it": [
            "paura",
            "spaventato",
            "spavento",
            "terrore",
            "terrorizzato",
            "fobia",
            "pauroso",
            "vigliacco",
            "coraggio",
        ],
        "de": [
            "angst",
            "furcht",
            "fürchten",
            "erschrocken",
            "schrecken",
            "terror",
            "phobie",
            "ängstlich",
            "mut",
            "feige",
        ],
        "es": [
            "miedo",
            "asustado",
            "susto",
            "terror",
            "aterrorizado",
            "fobia",
            "temeroso",
            "cobarde",
            "valentía",
        ],
        "fr": [
            "peur",
            "effrayé",
            "frayeur",
            "terreur",
            "terrorisé",
            "phobie",
            "craintif",
            "couard",
            "courage",
        ],
        "pt": [
            "medo",
            "assustado",
            "susto",
            "terror",
            "aterrorizado",
            "fobia",
            "medroso",
            "covarde",
            "coragem",
        ],
        "ar": [
            "خوف",
            "مخيف",
            "رعب",
            "فزع",
        ],
    },
    "hope": {
        "en": [
            "hope",
            "hopeful",
            "hopeless",
            "despair",
            "desperate",
            "discouraged",
            "future",
            "promise",
            "expectation",
            "optimism",
        ],
        "it": [
            "speranza",
            "speranzoso",
            "disperato",
            "disperazione",
            "scoraggiato",
            "futuro",
            "promessa",
            "aspettativa",
            "ottimismo",
        ],
        "de": [
            "hoffnung",
            "hoffnungsvoll",
            "hoffnungslos",
            "verzweiflung",
            "verzweifelt",
            "entmutigt",
            "zukunft",
            "versprechen",
            "optimismus",
        ],
        "es": [
            "esperanza",
            "esperanzado",
            "desesperado",
            "desesperación",
            "desanimado",
            "futuro",
            "promesa",
            "expectativa",
            "optimismo",
        ],
        "fr": [
            "espoir",
            "espérance",
            "plein d'espoir",
            "désespéré",
            "désespoir",
            "découragé",
            "futur",
            "promesse",
            "optimisme",
        ],
        "pt": [
            "esperança",
            "esperançoso",
            "desesperado",
            "desespero",
            "desanimado",
            "futuro",
            "promessa",
            "expectativa",
            "otimismo",
        ],
        "ar": [
            "أمل",
            "يأس",
            "مستقبل",
            "وعد",
        ],
    },
    "love": {
        "en": [
            "love",
            "loved",
            "unloved",
            "compassion",
            "kindness",
            "care",
            "relationship",
            "beloved",
            "cherish",
            "adore",
        ],
        "it": [
            "amore",
            "amato",
            "compassione",
            "gentilezza",
            "cura",
            "relazione",
            "amato",
            "adorare",
        ],
        "de": [
            "liebe",
            "geliebt",
            "mitgefühl",
            "güte",
            "fürsorge",
            "beziehung",
            "geliebte",
            "verehren",
        ],
        "es": [
            "amor",
            "amado",
            "compasión",
            "bondad",
            "cuidado",
            "relación",
            "adorar",
        ],
        "fr": [
            "amour",
            "aimé",
            "compassion",
            "bonté",
            "soin",
            "relation",
            "chéri",
            "adorer",
        ],
        "pt": [
            "amor",
            "amado",
            "compaixão",
            "bondade",
            "cuidado",
            "relacionamento",
            "adorar",
        ],
        "ar": [
            "حب",
            "محبة",
            "رحمة",
            "عطف",
        ],
    },
    "grief": {
        "en": [
            "grief",
            "grieve",
            "grieving",
            "mourning",
            "mourn",
            "loss",
            "lost",
            "sorrow",
            "sad",
            "sadness",
            "depression",
            "depressed",
            "heartbroken",
        ],
        "it": [
            "dolore",
            "lutto",
            "perdita",
            "tristezza",
            "triste",
            "depressione",
            "depresso",
            "cuore spezzato",
            "piangere",
        ],
        "de": [
            "trauer",
            "trauern",
            "verlust",
            "traurigkeit",
            "traurig",
            "depression",
            "deprimiert",
            "herzschmerz",
            "betrauern",
        ],
        "es": [
            "dolor",
            "duelo",
            "pérdida",
            "tristeza",
            "triste",
            "depresión",
            "deprimido",
            "corazón roto",
            "llorar",
        ],
        "fr": [
            "deuil",
            "douleur",
            "perte",
            "tristesse",
            "triste",
            "dépression",
            "déprimé",
            "cœur brisé",
            "pleurer",
        ],
        "pt": [
            "luto",
            "dor",
            "perda",
            "tristeza",
            "triste",
            "depressão",
            "deprimido",
            "coração partido",
            "chorar",
        ],
        "ar": [
            "حزن",
            "حداد",
            "خسارة",
            "فقدان",
        ],
    },
    "guidance": {
        "en": [
            "guidance",
            "guide",
            "direction",
            "lost",
            "confused",
            "decision",
            "wisdom",
            "path",
            "way",
            "purpose",
            "calling",
            "discernment",
        ],
        "it": [
            "guida",
            "direzione",
            "perso",
            "confuso",
            "decisione",
            "saggezza",
            "cammino",
            "scopo",
            "discernimento",
        ],
        "de": [
            "führung",
            "leitung",
            "richtung",
            "verloren",
            "verwirrt",
            "entscheidung",
            "weisheit",
            "weg",
            "zweck",
            "berufung",
        ],
        "es": [
            "guía",
            "dirección",
            "perdido",
            "confundido",
            "decisión",
            "sabiduría",
            "camino",
            "propósito",
            "discernimiento",
        ],
        "fr": [
            "guide",
            "direction",
            "perdu",
            "confus",
            "décision",
            "sagesse",
            "chemin",
            "but",
            "discernement",
        ],
        "pt": [
            "guia",
            "direção",
            "perdido",
            "confuso",
            "decisão",
            "sabedoria",
            "caminho",
            "propósito",
            "discernimento",
        ],
        "ar": [
            "هداية",
            "إرشاد",
            "ضائع",
            "قرار",
            "حكمة",
        ],
    },
    "patience": {
        "en": [
            "patience",
            "patient",
            "impatient",
            "waiting",
            "wait",
            "endure",
            "endurance",
            "persevere",
            "perseverance",
            "long-suffering",
        ],
        "it": [
            "pazienza",
            "paziente",
            "impaziente",
            "aspettare",
            "aspettativa",
            "sopportare",
            "sopportazione",
            "perseverare",
            "perseveranza",
        ],
        "de": [
            "geduld",
            "geduldig",
            "ungeduldig",
            "warten",
            "ausdauer",
            "ertragen",
            "durchhalten",
            "beharrlichkeit",
        ],
        "es": [
            "paciencia",
            "paciente",
            "impaciente",
            "esperar",
            "espera",
            "soportar",
            "perseverar",
            "perseverancia",
        ],
        "fr": [
            "patience",
            "patient",
            "impatient",
            "attendre",
            "attente",
            "endurer",
            "persévérer",
            "persévérance",
        ],
        "pt": [
            "paciência",
            "paciente",
            "impaciente",
            "esperar",
            "espera",
            "suportar",
            "perseverar",
            "perseverança",
        ],
        "ar": [
            "صبر",
            "صابر",
            "انتظار",
            "تحمل",
        ],
    },
    "joy": {
        "en": [
            "joy",
            "joyful",
            "happy",
            "happiness",
            "gladness",
            "rejoice",
            "delight",
            "cheerful",
            "blessed",
            "blessings",
        ],
        "it": [
            "gioia",
            "gioioso",
            "felice",
            "felicità",
            "letizia",
            "rallegrarsi",
            "delizia",
            "allegro",
            "benedetto",
            "benedizioni",
        ],
        "de": [
            "freude",
            "fröhlich",
            "glücklich",
            "glück",
            "frohlocken",
            "entzücken",
            "heiter",
            "gesegnet",
            "segnungen",
        ],
        "es": [
            "alegría",
            "gozoso",
            "feliz",
            "felicidad",
            "regocijarse",
            "deleite",
            "animado",
            "bendecido",
            "bendiciones",
        ],
        "fr": [
            "joie",
            "joyeux",
            "heureux",
            "bonheur",
            "se réjouir",
            "délice",
            "gai",
            "béni",
            "bénédictions",
        ],
        "pt": [
            "alegria",
            "alegre",
            "feliz",
            "felicidade",
            "rejubilar",
            "prazer",
            "animado",
            "abençoado",
            "bênçãos",
        ],
        "ar": [
            "فرح",
            "سعادة",
            "بهجة",
            "مباركة",
        ],
    },
}

# Language codes with keyword coverage, in a stable canonical order.
SUPPORTED_TOPIC_LANGUAGES: tuple[str, ...] = ("en", "it", "de", "es", "fr", "pt", "ar")


def canonical_topics() -> frozenset[str]:
    """Return the canonical topic-id vocabulary (BITB-103).

    Single source of truth for anything that needs to validate a topic id
    against "the 13 topics this app knows about" — e.g. the golden-set
    schema (``search_eval.models.GoldenCase.topics``) — without duplicating
    this list by hand.
    """
    return frozenset(TOPIC_KEYWORDS_BY_LANGUAGE)


def _flatten(by_language: dict[str, dict[str, list[str]]]) -> dict[str, list[str]]:
    """Flatten the per-language keyword map into the legacy topic -> keywords shape.

    Order-preserving de-dupe (a handful of keywords repeat verbatim across
    languages, e.g. "stress" in EN/IT/DE) so downstream consumers that just
    need "does any keyword match" keep working unchanged.
    """
    flattened: dict[str, list[str]] = {}
    for topic, lang_map in by_language.items():
        seen: set[str] = set()
        keywords: list[str] = []
        for lang in SUPPORTED_TOPIC_LANGUAGES:
            for keyword in lang_map.get(lang, []):
                if keyword not in seen:
                    seen.add(keyword)
                    keywords.append(keyword)
        flattened[topic] = keywords
    return flattened


# Maps topic names to lists of keywords/phrases across 7 languages (EN, IT,
# DE, ES, FR, PT, AR), flattened from TOPIC_KEYWORDS_BY_LANGUAGE for callers
# (e.g. detect_topics below) that only need "does any keyword match".
TOPIC_KEYWORD_MAP: dict[str, list[str]] = _flatten(TOPIC_KEYWORDS_BY_LANGUAGE)


def detect_topics(message: str) -> list[str]:
    """
    Detect biblical topics in user message using keyword matching.

    Fast O(n*k) keyword scan — no LLM or NLP required.
    Typical runtime: <1ms for normal messages.

    Args:
        message: User's message text

    Returns:
        List of detected topic names (may be empty)
    """
    start_time = time.monotonic()
    message_lower = message.lower()
    detected: list[str] = []

    for topic, keywords in TOPIC_KEYWORD_MAP.items():
        if any(keyword in message_lower for keyword in keywords):
            detected.append(topic)

    elapsed_ms = (time.monotonic() - start_time) * 1000
    logger.debug(
        "Topic detection completed",
        extra={
            "message_length": len(message),
            "detected_topics": detected,
            "elapsed_ms": round(elapsed_ms, 2),
        },
    )

    return detected
