package org.voxquieta.app.utils

/**
 * Bundled fallback map of localized Bible book names (lowercased) to their canonical
 * English book names (lowercased).
 *
 * This is the Android copy of the canonical map at tests/fixtures/localized_book_map.json
 * (BITB-059), which in turn mirrors the backend source of truth
 * (api/utils/translation_registry.py). It lets verse detection and normalization work
 * offline / before the /api/v1/scripture/book-names call returns. Runtime API data is
 * merged on top of — never replaced by — this map.
 *
 * @generated from tests/fixtures/localized_book_map.json by
 * scripts/generate_localized_book_map.py — DO NOT EDIT individual entries by hand. Edit the
 * JSON and re-run the generator; LocalizedBookToEnglishTest checks content equivalence
 * against the JSON so drift fails CI.
 */
internal val LOCALIZED_BOOK_TO_ENGLISH: Map<String, String> = mapOf(
    "psalm" to "psalms",
    "song of solomon" to "song of solomon",
    "genesi" to "genesis",
    "esodo" to "exodus",
    "levitico" to "leviticus",
    "numeri" to "numbers",
    "deuteronomio" to "deuteronomy",
    "giosuè" to "joshua",
    "giudici" to "judges",
    "rut" to "ruth",
    "1 samuele" to "1 samuel",
    "2 samuele" to "2 samuel",
    "1 re" to "1 kings",
    "2 re" to "2 kings",
    "1 cronache" to "1 chronicles",
    "2 cronache" to "2 chronicles",
    "esdra" to "ezra",
    "nehemia" to "nehemiah",
    "ester" to "esther",
    "giobbe" to "job",
    "salmi" to "psalms",
    "salmo" to "psalms",
    "proverbi" to "proverbs",
    "ecclesiaste" to "ecclesiastes",
    "cantico dei cantici" to "song of solomon",
    "isaia" to "isaiah",
    "geremia" to "jeremiah",
    "lamentazioni" to "lamentations",
    "ezechiele" to "ezekiel",
    "daniele" to "daniel",
    "osea" to "hosea",
    "gioele" to "joel",
    "abdia" to "obadiah",
    "giona" to "jonah",
    "michea" to "micah",
    "abacuc" to "habakkuk",
    "sofonia" to "zephaniah",
    "aggeo" to "haggai",
    "zaccaria" to "zechariah",
    "malachia" to "malachi",
    "matteo" to "matthew",
    "marco" to "mark",
    "luca" to "luke",
    "giovanni" to "john",
    "atti" to "acts",
    "romani" to "romans",
    "1 corinzi" to "1 corinthians",
    "2 corinzi" to "2 corinthians",
    "galati" to "galatians",
    "efesini" to "ephesians",
    "filippesi" to "philippians",
    "colossesi" to "colossians",
    "1 tessalonicesi" to "1 thessalonians",
    "2 tessalonicesi" to "2 thessalonians",
    "1 timoteo" to "1 timothy",
    "2 timoteo" to "2 timothy",
    "tito" to "titus",
    "filemone" to "philemon",
    "ebrei" to "hebrews",
    "giacomo" to "james",
    "1 pietro" to "1 peter",
    "2 pietro" to "2 peter",
    "1 giovanni" to "1 john",
    "2 giovanni" to "2 john",
    "3 giovanni" to "3 john",
    "giuda" to "jude",
    "apocalisse" to "revelation",
    "1. mose" to "genesis",
    "2. mose" to "exodus",
    "3. mose" to "leviticus",
    "4. mose" to "numbers",
    "5. mose" to "deuteronomy",
    "josua" to "joshua",
    "richter" to "judges",
    "ruth" to "ruth",
    "1. samuel" to "1 samuel",
    "2. samuel" to "2 samuel",
    "1. könige" to "1 kings",
    "2. könige" to "2 kings",
    "1. chronik" to "1 chronicles",
    "2. chronik" to "2 chronicles",
    "esra" to "ezra",
    "hiob" to "job",
    "psalmen" to "psalms",
    "sprüche" to "proverbs",
    "prediger" to "ecclesiastes",
    "hohelied" to "song of solomon",
    "hohes lied" to "song of solomon",
    "jesaja" to "isaiah",
    "jeremia" to "jeremiah",
    "klagelieder" to "lamentations",
    "hesekiel" to "ezekiel",
    "obadja" to "obadiah",
    "jona" to "jonah",
    "micha" to "micah",
    "habakuk" to "habakkuk",
    "zephanja" to "zephaniah",
    "zefanja" to "zephaniah",
    "sacharja" to "zechariah",
    "maleachi" to "malachi",
    "matthäus" to "matthew",
    "markus" to "mark",
    "lukas" to "luke",
    "johannes" to "john",
    "apostelgeschichte" to "acts",
    "römer" to "romans",
    "1. korinther" to "1 corinthians",
    "2. korinther" to "2 corinthians",
    "galater" to "galatians",
    "epheser" to "ephesians",
    "philipper" to "philippians",
    "kolosser" to "colossians",
    "1. thessalonicher" to "1 thessalonians",
    "2. thessalonicher" to "2 thessalonians",
    "1. timotheus" to "1 timothy",
    "2. timotheus" to "2 timothy",
    "titus" to "titus",
    "philemon" to "philemon",
    "hebräer" to "hebrews",
    "jakobus" to "james",
    "1. petrus" to "1 peter",
    "2. petrus" to "2 peter",
    "1. johannes" to "1 john",
    "2. johannes" to "2 john",
    "3. johannes" to "3 john",
    "judas" to "jude",
    "offenbarung" to "revelation",
    "génesis" to "genesis",
    "éxodo" to "exodus",
    "levítico" to "leviticus",
    "números" to "numbers",
    "josué" to "joshua",
    "jueces" to "judges",
    "1 reyes" to "1 kings",
    "2 reyes" to "2 kings",
    "1 crónicas" to "1 chronicles",
    "2 crónicas" to "2 chronicles",
    "esdras" to "ezra",
    "nehemías" to "nehemiah",
    "salmos" to "psalms",
    "proverbios" to "proverbs",
    "eclesiastés" to "ecclesiastes",
    "cantares" to "song of solomon",
    "isaías" to "isaiah",
    "jeremías" to "jeremiah",
    "lamentaciones" to "lamentations",
    "ezequiel" to "ezekiel",
    "oseas" to "hosea",
    "amós" to "amos",
    "abdías" to "obadiah",
    "jonás" to "jonah",
    "miqueas" to "micah",
    "nahúm" to "nahum",
    "sofonías" to "zephaniah",
    "hageo" to "haggai",
    "zacarías" to "zechariah",
    "malaquías" to "malachi",
    "mateo" to "matthew",
    "marcos" to "mark",
    "lucas" to "luke",
    "juan" to "john",
    "hechos" to "acts",
    "romanos" to "romans",
    "1 corintios" to "1 corinthians",
    "2 corintios" to "2 corinthians",
    "gálatas" to "galatians",
    "efesios" to "ephesians",
    "filipenses" to "philippians",
    "colosenses" to "colossians",
    "1 tesalonicenses" to "1 thessalonians",
    "2 tesalonicenses" to "2 thessalonians",
    "filemón" to "philemon",
    "hebreos" to "hebrews",
    "santiago" to "james",
    "1 pedro" to "1 peter",
    "2 pedro" to "2 peter",
    "1 juan" to "1 john",
    "2 juan" to "2 john",
    "3 juan" to "3 john",
    "apocalipsis" to "revelation",
    "genèse" to "genesis",
    "exode" to "exodus",
    "lévitique" to "leviticus",
    "nombres" to "numbers",
    "deutéronome" to "deuteronomy",
    "juges" to "judges",
    "1 rois" to "1 kings",
    "2 rois" to "2 kings",
    "1 chroniques" to "1 chronicles",
    "2 chroniques" to "2 chronicles",
    "néhémie" to "nehemiah",
    "psaumes" to "psalms",
    "psaume" to "psalms",
    "proverbes" to "proverbs",
    "ecclésiaste" to "ecclesiastes",
    "cantique des cantiques" to "song of solomon",
    "ésaïe" to "isaiah",
    "jérémie" to "jeremiah",
    "ézéchiel" to "ezekiel",
    "osée" to "hosea",
    "joël" to "joel",
    "abdias" to "obadiah",
    "jonas" to "jonah",
    "michée" to "micah",
    "sophonie" to "zephaniah",
    "aggée" to "haggai",
    "zacharie" to "zechariah",
    "malachie" to "malachi",
    "matthieu" to "matthew",
    "marc" to "mark",
    "luc" to "luke",
    "jean" to "john",
    "actes des apôtres" to "acts",
    "romains" to "romans",
    "1 corinthiens" to "1 corinthians",
    "2 corinthiens" to "2 corinthians",
    "galates" to "galatians",
    "éphésiens" to "ephesians",
    "philippiens" to "philippians",
    "colossiens" to "colossians",
    "1 thessaloniciens" to "1 thessalonians",
    "2 thessaloniciens" to "2 thessalonians",
    "1 timothée" to "1 timothy",
    "2 timothée" to "2 timothy",
    "tite" to "titus",
    "philémon" to "philemon",
    "hébreux" to "hebrews",
    "jacques" to "james",
    "1 pierre" to "1 peter",
    "2 pierre" to "2 peter",
    "1 jean" to "1 john",
    "2 jean" to "2 john",
    "3 jean" to "3 john",
    "jude" to "jude",
    "apocalypse" to "revelation",
    "gênesis" to "genesis",
    "êxodo" to "exodus",
    "deuteronômio" to "deuteronomy",
    "juízes" to "judges",
    "rute" to "ruth",
    "1 reis" to "1 kings",
    "2 reis" to "2 kings",
    "1 crônicas" to "1 chronicles",
    "2 crônicas" to "2 chronicles",
    "neemias" to "nehemiah",
    "jó" to "job",
    "provérbios" to "proverbs",
    "eclesiastes" to "ecclesiastes",
    "cântico dos cânticos" to "song of solomon",
    "jeremias" to "jeremiah",
    "lamentações" to "lamentations",
    "oseias" to "hosea",
    "obadias" to "obadiah",
    "miquéias" to "micah",
    "naum" to "nahum",
    "habacuque" to "habakkuk",
    "sofonias" to "zephaniah",
    "ageu" to "haggai",
    "zacarias" to "zechariah",
    "malaquias" to "malachi",
    "mateus" to "matthew",
    "joão" to "john",
    "atos" to "acts",
    "1 coríntios" to "1 corinthians",
    "2 coríntios" to "2 corinthians",
    "efésios" to "ephesians",
    "colossenses" to "colossians",
    "1 tessalonicenses" to "1 thessalonians",
    "2 tessalonicenses" to "2 thessalonians",
    "1 timóteo" to "1 timothy",
    "2 timóteo" to "2 timothy",
    "filemom" to "philemon",
    "hebreus" to "hebrews",
    "tiago" to "james",
    "1 joão" to "1 john",
    "2 joão" to "2 john",
    "3 joão" to "3 john",
    "apocalipse" to "revelation",
    "تكوين" to "genesis",
    "خروج" to "exodus",
    "لاويين" to "leviticus",
    "عدد" to "numbers",
    "تثنية" to "deuteronomy",
    "يشوع" to "joshua",
    "القضاة" to "judges",
    "قضاة" to "judges",
    "راعوث" to "ruth",
    "1 صموئيل" to "1 samuel",
    "2 صموئيل" to "2 samuel",
    "1 الملوك" to "1 kings",
    "2 الملوك" to "2 kings",
    "1 ملوك" to "1 kings",
    "2 ملوك" to "2 kings",
    "1 أخبار الأيام" to "1 chronicles",
    "2 أخبار الأيام" to "2 chronicles",
    "عزرا" to "ezra",
    "نحميا" to "nehemiah",
    "أستير" to "esther",
    "أيوب" to "job",
    "المزامير" to "psalms",
    "مزمور" to "psalms",
    "مزامير" to "psalms",
    "الأمثال" to "proverbs",
    "أمثال" to "proverbs",
    "الجامعة" to "ecclesiastes",
    "جامعة" to "ecclesiastes",
    "نشيد الأنشاد" to "song of solomon",
    "نشيد الأناشيد" to "song of solomon",
    "إشعياء" to "isaiah",
    "إرميا" to "jeremiah",
    "مراثي إرميا" to "lamentations",
    "حزقيال" to "ezekiel",
    "دانيال" to "daniel",
    "هوشع" to "hosea",
    "يوئيل" to "joel",
    "عاموس" to "amos",
    "عوبديا" to "obadiah",
    "يونان" to "jonah",
    "ميخا" to "micah",
    "ناحوم" to "nahum",
    "حبقوق" to "habakkuk",
    "صفنيا" to "zephaniah",
    "حجي" to "haggai",
    "زكريا" to "zechariah",
    "ملاخي" to "malachi",
    "متى" to "matthew",
    "مرقس" to "mark",
    "لوقا" to "luke",
    "يوحنا" to "john",
    "أعمال الرسل" to "acts",
    "أعمال" to "acts",
    "رومية" to "romans",
    "1 كورنثوس" to "1 corinthians",
    "2 كورنثوس" to "2 corinthians",
    "غلاطية" to "galatians",
    "أفسس" to "ephesians",
    "فيليبي" to "philippians",
    "كولوسي" to "colossians",
    "1 تسالونيكي" to "1 thessalonians",
    "2 تسالونيكي" to "2 thessalonians",
    "1 تيموثاوس" to "1 timothy",
    "2 تيموثاوس" to "2 timothy",
    "تيطس" to "titus",
    "فليمون" to "philemon",
    "عبرانيين" to "hebrews",
    "يعقوب" to "james",
    "1 بطرس" to "1 peter",
    "2 بطرس" to "2 peter",
    "1 يوحنا" to "1 john",
    "2 يوحنا" to "2 john",
    "3 يوحنا" to "3 john",
    "يهوذا" to "jude",
    "الرؤيا" to "revelation",
    "رؤيا" to "revelation",
    "उत्पत्ति" to "genesis",
    "निर्गमन" to "exodus",
    "लैव्यव्यवस्था" to "leviticus",
    "लेवियतियुस" to "leviticus",
    "गिनती" to "numbers",
    "व्यवस्थाविवरण" to "deuteronomy",
    "यहोशू" to "joshua",
    "न्यायियों" to "judges",
    "रूत" to "ruth",
    "1 शमूएल" to "1 samuel",
    "2 शमूएल" to "2 samuel",
    "1 राजाओं" to "1 kings",
    "2 राजाओं" to "2 kings",
    "1 इतिहास" to "1 chronicles",
    "2 इतिहास" to "2 chronicles",
    "एज्रा" to "ezra",
    "नहेम्याह" to "nehemiah",
    "एस्तेर" to "esther",
    "अय्यूब" to "job",
    "भजन संहिता" to "psalms",
    "नीतिवचन" to "proverbs",
    "सभोपदेशक" to "ecclesiastes",
    "श्रेष्ठगीत" to "song of solomon",
    "यशायाह" to "isaiah",
    "यिर्मयाह" to "jeremiah",
    "विलापगीत" to "lamentations",
    "यहेजकेल" to "ezekiel",
    "दानिय्येल" to "daniel",
    "होशे" to "hosea",
    "योएल" to "joel",
    "आमोस" to "amos",
    "ओबद्याह" to "obadiah",
    "योना" to "jonah",
    "मीका" to "micah",
    "नहूम" to "nahum",
    "हबक्कूक" to "habakkuk",
    "सपन्याह" to "zephaniah",
    "हाग्गै" to "haggai",
    "जकर्याह" to "zechariah",
    "मलाकी" to "malachi",
    "मत्ती" to "matthew",
    "मरकुस" to "mark",
    "लूका" to "luke",
    "यूहन्ना" to "john",
    "प्रेरितों के काम" to "acts",
    "रोमियों" to "romans",
    "1 कुरिन्थियों" to "1 corinthians",
    "2 कुरिन्थियों" to "2 corinthians",
    "गलातियों" to "galatians",
    "इफिसियों" to "ephesians",
    "फिलिप्पियों" to "philippians",
    "कुलुस्सियों" to "colossians",
    "1 थिस्सलुनीकियों" to "1 thessalonians",
    "2 थिस्सलुनीकियों" to "2 thessalonians",
    "1 तीमुथियुस" to "1 timothy",
    "2 तीमुथियुस" to "2 timothy",
    "तीतुस" to "titus",
    "फिलेमोन" to "philemon",
    "इब्रानियों" to "hebrews",
    "याकूब" to "james",
    "न्यायियो" to "judges",
    "1 राजाओ" to "1 kings",
    "2 राजाओ" to "2 kings",
    "रोमियो" to "romans",
    "1 कुरिन्थियो" to "1 corinthians",
    "2 कुरिन्थियो" to "2 corinthians",
    "गलातियो" to "galatians",
    "इफिसियो" to "ephesians",
    "कुलुस्सियो" to "colossians",
    "1 थिस्सलुनीकियो" to "1 thessalonians",
    "2 थिस्सलुनीकियो" to "2 thessalonians",
    "इब्रानियो" to "hebrews",
    "1 पतरस" to "1 peter",
    "2 पतरस" to "2 peter",
    "1 यूहन्ना" to "1 john",
    "2 यूहन्ना" to "2 john",
    "3 यूहन्ना" to "3 john",
    "यहूदा" to "jude",
    "प्रकाशितवाक्य" to "revelation",
    "бытие" to "genesis",
    "исход" to "exodus",
    "левит" to "leviticus",
    "числа" to "numbers",
    "второзаконие" to "deuteronomy",
    "иисус навин" to "joshua",
    "судьи" to "judges",
    "руфь" to "ruth",
    "1 царств" to "1 samuel",
    "2 царств" to "2 samuel",
    "3 царств" to "1 kings",
    "4 царств" to "2 kings",
    "1 паралипоменон" to "1 chronicles",
    "2 паралипоменон" to "2 chronicles",
    "ездра" to "ezra",
    "неемия" to "nehemiah",
    "есфирь" to "esther",
    "иов" to "job",
    "псалтирь" to "psalms",
    "притчи" to "proverbs",
    "екклесиаст" to "ecclesiastes",
    "песня песней" to "song of solomon",
    "песни песней" to "song of solomon",
    "исаия" to "isaiah",
    "иеремия" to "jeremiah",
    "плач иеремии" to "lamentations",
    "иезекиль" to "ezekiel",
    "даниил" to "daniel",
    "осия" to "hosea",
    "иоиль" to "joel",
    "амос" to "amos",
    "авдий" to "obadiah",
    "иона" to "jonah",
    "михей" to "micah",
    "наум" to "nahum",
    "аввакум" to "habakkuk",
    "софония" to "zephaniah",
    "аггей" to "haggai",
    "захария" to "zechariah",
    "малахия" to "malachi",
    "матфей" to "matthew",
    "марк" to "mark",
    "лука" to "luke",
    "иоанн" to "john",
    "деяния апостолов" to "acts",
    "деяния" to "acts",
    "римлянам" to "romans",
    "1 коринфянам" to "1 corinthians",
    "2 коринфянам" to "2 corinthians",
    "галатам" to "galatians",
    "ефесянам" to "ephesians",
    "филиппийцам" to "philippians",
    "колоссянам" to "colossians",
    "1 фессалоникийцам" to "1 thessalonians",
    "2 фессалоникийцам" to "2 thessalonians",
    "1 тимофею" to "1 timothy",
    "2 тимофею" to "2 timothy",
    "титу" to "titus",
    "филимону" to "philemon",
    "евреям" to "hebrews",
    "иаков" to "james",
    "1 петра" to "1 peter",
    "2 петра" to "2 peter",
    "1 иоанна" to "1 john",
    "2 иоанна" to "2 john",
    "3 иоанна" to "3 john",
    "иуда" to "jude",
    "откровение" to "revelation",
    "ин" to "john",
    "мф" to "matthew",
    "мк" to "mark",
    "лк" to "luke",
    "пс" to "psalms",
    "рим" to "romans",
    "быт" to "genesis",
    "ис" to "isaiah",
    "откр" to "revelation",
    "деян" to "acts",
    "гал" to "galatians",
    "еф" to "ephesians",
    "кол" to "colossians",
    "евр" to "hebrews",
    "иак" to "james",
    "флп" to "philippians",
    "флм" to "philemon",
    "иёв" to "job",
    "бытия" to "genesis",
    "исхода" to "exodus",
    "левита" to "leviticus",
    "числ" to "numbers",
    "второзакония" to "deuteronomy",
    "руфи" to "ruth",
    "псалтири" to "psalms",
    "притч" to "proverbs",
    "екклесиаста" to "ecclesiastes",
    "исаии" to "isaiah",
    "иеремии" to "jeremiah",
    "иезекиля" to "ezekiel",
    "даниила" to "daniel",
    "осии" to "hosea",
    "иоиля" to "joel",
    "ионы" to "jonah",
    "михея" to "micah",
    "наума" to "nahum",
    "аввакума" to "habakkuk",
    "софонии" to "zephaniah",
    "аггея" to "haggai",
    "захарии" to "zechariah",
    "малахии" to "malachi",
    "матфея" to "matthew",
    "марка" to "mark",
    "луки" to "luke",
    "иоанна" to "john",
    "деяний" to "acts",
    "иакова" to "james",
    "иуды" to "jude",
    "откровения" to "revelation",
    "1-я царств" to "1 samuel",
    "2-я царств" to "2 samuel",
    "3-я царств" to "1 kings",
    "4-я царств" to "2 kings",
    "1-я паралипоменон" to "1 chronicles",
    "2-я паралипоменон" to "2 chronicles",
    "1-е коринфянам" to "1 corinthians",
    "2-е коринфянам" to "2 corinthians",
    "1-е фессалоникийцам" to "1 thessalonians",
    "2-е фессалоникийцам" to "2 thessalonians",
    "1-е тимофею" to "1 timothy",
    "2-е тимофею" to "2 timothy",
    "1-е петра" to "1 peter",
    "2-е петра" to "2 peter",
    "1-е иоанна" to "1 john",
    "2-е иоанна" to "2 john",
    "3-е иоанна" to "3 john",
    "2-я петра" to "2 peter",
    "创世记" to "genesis",
    "创世纪" to "genesis",
    "出埃及记" to "exodus",
    "利未记" to "leviticus",
    "民数记" to "numbers",
    "申命记" to "deuteronomy",
    "约书亚记" to "joshua",
    "士师记" to "judges",
    "路得记" to "ruth",
    "撒母耳记上" to "1 samuel",
    "撒母耳记下" to "2 samuel",
    "列王纪上" to "1 kings",
    "列王纪下" to "2 kings",
    "历代志上" to "1 chronicles",
    "历代志下" to "2 chronicles",
    "以斯拉记" to "ezra",
    "尼希米记" to "nehemiah",
    "以斯帖记" to "esther",
    "约伯记" to "job",
    "诗篇" to "psalms",
    "箴言" to "proverbs",
    "传道书" to "ecclesiastes",
    "雅歌" to "song of solomon",
    "以赛亚书" to "isaiah",
    "耶利米书" to "jeremiah",
    "耶利米哀歌" to "lamentations",
    "以西结书" to "ezekiel",
    "但以理书" to "daniel",
    "何西阿书" to "hosea",
    "约珥书" to "joel",
    "阿摩司书" to "amos",
    "俄巴底亚书" to "obadiah",
    "约拿书" to "jonah",
    "弥迦书" to "micah",
    "那鸿书" to "nahum",
    "哈巴谷书" to "habakkuk",
    "西番雅书" to "zephaniah",
    "哈该书" to "haggai",
    "撒迦利亚书" to "zechariah",
    "玛拉基书" to "malachi",
    "马太福音" to "matthew",
    "马可福音" to "mark",
    "路加福音" to "luke",
    "约翰福音" to "john",
    "使徒行传" to "acts",
    "罗马书" to "romans",
    "哥林多前书" to "1 corinthians",
    "哥林多后书" to "2 corinthians",
    "加拉太书" to "galatians",
    "以弗所书" to "ephesians",
    "腓立比书" to "philippians",
    "歌罗西书" to "colossians",
    "帖撒罗尼迦前书" to "1 thessalonians",
    "帖撒罗尼迦后书" to "2 thessalonians",
    "提摩太前书" to "1 timothy",
    "提摩太后书" to "2 timothy",
    "提多书" to "titus",
    "腓利门书" to "philemon",
    "希伯来书" to "hebrews",
    "雅各书" to "james",
    "彼得前书" to "1 peter",
    "彼得后书" to "2 peter",
    "约翰一书" to "1 john",
    "约翰二书" to "2 john",
    "约翰三书" to "3 john",
    "犹大书" to "jude",
    "启示录" to "revelation",
    "出埃及纪" to "exodus",
    "利未纪" to "leviticus",
    "民数纪" to "numbers",
    "申命纪" to "deuteronomy",
    "约书亚纪" to "joshua",
    "士师纪" to "judges",
    "路得纪" to "ruth",
    "撒母耳纪上" to "1 samuel",
    "撒母耳纪下" to "2 samuel",
    "列王记上" to "1 kings",
    "列王记下" to "2 kings",
    "以斯拉纪" to "ezra",
    "尼希米纪" to "nehemiah",
    "以斯帖纪" to "esther",
    "约伯纪" to "job",
    "玛窦福音" to "matthew",
    "马尔谷福音" to "mark",
    "若望福音" to "john",
    "宗徒大事录" to "acts",
    "默示录" to "revelation",
    "格林多前书" to "1 corinthians",
    "格林多后书" to "2 corinthians",
    "若望一书" to "1 john",
    "若望二书" to "2 john",
    "若望三书" to "3 john",
    "雅各伯书" to "james",
    "犹达书" to "jude",
    "창세기" to "genesis",
    "출애굽기" to "exodus",
    "레위기" to "leviticus",
    "민수기" to "numbers",
    "신명기" to "deuteronomy",
    "여호수아" to "joshua",
    "사사기" to "judges",
    "룻기" to "ruth",
    "사무엘상" to "1 samuel",
    "사무엘하" to "2 samuel",
    "열왕기상" to "1 kings",
    "열왕기하" to "2 kings",
    "역대상" to "1 chronicles",
    "역대하" to "2 chronicles",
    "에스라" to "ezra",
    "느헤미야" to "nehemiah",
    "에스더" to "esther",
    "욥기" to "job",
    "시편" to "psalms",
    "잠언" to "proverbs",
    "전도서" to "ecclesiastes",
    "아가" to "song of solomon",
    "이사야" to "isaiah",
    "예레미야" to "jeremiah",
    "예레미야애가" to "lamentations",
    "예레미야 애가" to "lamentations",
    "에스겔" to "ezekiel",
    "다니엘" to "daniel",
    "호세아" to "hosea",
    "요엘" to "joel",
    "아모스" to "amos",
    "오바댜" to "obadiah",
    "요나" to "jonah",
    "미가" to "micah",
    "나훔" to "nahum",
    "하박국" to "habakkuk",
    "스바냐" to "zephaniah",
    "학개" to "haggai",
    "스가랴" to "zechariah",
    "말라기" to "malachi",
    "마태복음" to "matthew",
    "마가복음" to "mark",
    "누가복음" to "luke",
    "요한복음" to "john",
    "사도행전" to "acts",
    "로마서" to "romans",
    "고린도전서" to "1 corinthians",
    "고린도후서" to "2 corinthians",
    "갈라디아서" to "galatians",
    "에베소서" to "ephesians",
    "빌립보서" to "philippians",
    "골로새서" to "colossians",
    "데살로니가전서" to "1 thessalonians",
    "데살로니가후서" to "2 thessalonians",
    "디모데전서" to "1 timothy",
    "디모데후서" to "2 timothy",
    "디도서" to "titus",
    "빌레몬서" to "philemon",
    "히브리서" to "hebrews",
    "야고보서" to "james",
    "베드로전서" to "1 peter",
    "베드로후서" to "2 peter",
    "요한일서" to "1 john",
    "요한이서" to "2 john",
    "요한삼서" to "3 john",
    "유다서" to "jude",
    "요한계시록" to "revelation",
    "계시록" to "revelation",
    "애가" to "lamentations",
    "행전" to "acts",
)
