/**
 * Bundled fallback map of localized Bible book names (lowercased) to their canonical
 * English book names (lowercased).
 *
 * Canonical source: tests/fixtures/localized_book_map.json (BITB-059). The Android copy
 * (android/.../utils/LocalizedBookToEnglish.kt) is generated from the same file. The
 * backend's own map (api/utils/translation_registry.py) is a separate master, held
 * contradiction-free by api/tests/test_localized_book_map_registry_parity.py.
 *
 * Runtime API data from /api/v1/scripture/book-names is merged on top of — never
 * replaces — this map, via updateBookNames() in verseExtraction.ts.
 *
 * @generated from tests/fixtures/localized_book_map.json by
 * scripts/generate_localized_book_map.py — DO NOT EDIT individual entries by hand. Edit
 * the JSON and re-run the generator.
 */
// prettier-ignore
export const LOCALIZED_BOOK_TO_ENGLISH: Record<string, string> = {
  "psalm": "psalms",
  "song of solomon": "song of solomon",
  "genesi": "genesis",
  "esodo": "exodus",
  "levitico": "leviticus",
  "numeri": "numbers",
  "deuteronomio": "deuteronomy",
  "giosuè": "joshua",
  "giudici": "judges",
  "rut": "ruth",
  "1 samuele": "1 samuel",
  "2 samuele": "2 samuel",
  "1 re": "1 kings",
  "2 re": "2 kings",
  "1 cronache": "1 chronicles",
  "2 cronache": "2 chronicles",
  "esdra": "ezra",
  "nehemia": "nehemiah",
  "ester": "esther",
  "giobbe": "job",
  "salmi": "psalms",
  "salmo": "psalms",
  "proverbi": "proverbs",
  "ecclesiaste": "ecclesiastes",
  "cantico dei cantici": "song of solomon",
  "isaia": "isaiah",
  "geremia": "jeremiah",
  "lamentazioni": "lamentations",
  "ezechiele": "ezekiel",
  "daniele": "daniel",
  "osea": "hosea",
  "gioele": "joel",
  "abdia": "obadiah",
  "giona": "jonah",
  "michea": "micah",
  "abacuc": "habakkuk",
  "sofonia": "zephaniah",
  "aggeo": "haggai",
  "zaccaria": "zechariah",
  "malachia": "malachi",
  "matteo": "matthew",
  "marco": "mark",
  "luca": "luke",
  "giovanni": "john",
  "atti": "acts",
  "romani": "romans",
  "1 corinzi": "1 corinthians",
  "2 corinzi": "2 corinthians",
  "galati": "galatians",
  "efesini": "ephesians",
  "filippesi": "philippians",
  "colossesi": "colossians",
  "1 tessalonicesi": "1 thessalonians",
  "2 tessalonicesi": "2 thessalonians",
  "1 timoteo": "1 timothy",
  "2 timoteo": "2 timothy",
  "tito": "titus",
  "filemone": "philemon",
  "ebrei": "hebrews",
  "giacomo": "james",
  "1 pietro": "1 peter",
  "2 pietro": "2 peter",
  "1 giovanni": "1 john",
  "2 giovanni": "2 john",
  "3 giovanni": "3 john",
  "giuda": "jude",
  "apocalisse": "revelation",
  "1. mose": "genesis",
  "2. mose": "exodus",
  "3. mose": "leviticus",
  "4. mose": "numbers",
  "5. mose": "deuteronomy",
  "josua": "joshua",
  "richter": "judges",
  "ruth": "ruth",
  "1. samuel": "1 samuel",
  "2. samuel": "2 samuel",
  "1. könige": "1 kings",
  "2. könige": "2 kings",
  "1. chronik": "1 chronicles",
  "2. chronik": "2 chronicles",
  "esra": "ezra",
  "hiob": "job",
  "psalmen": "psalms",
  "sprüche": "proverbs",
  "prediger": "ecclesiastes",
  "hohelied": "song of solomon",
  "hohes lied": "song of solomon",
  "jesaja": "isaiah",
  "jeremia": "jeremiah",
  "klagelieder": "lamentations",
  "hesekiel": "ezekiel",
  "obadja": "obadiah",
  "jona": "jonah",
  "micha": "micah",
  "habakuk": "habakkuk",
  "zephanja": "zephaniah",
  "zefanja": "zephaniah",
  "sacharja": "zechariah",
  "maleachi": "malachi",
  "matthäus": "matthew",
  "markus": "mark",
  "lukas": "luke",
  "johannes": "john",
  "apostelgeschichte": "acts",
  "römer": "romans",
  "1. korinther": "1 corinthians",
  "2. korinther": "2 corinthians",
  "galater": "galatians",
  "epheser": "ephesians",
  "philipper": "philippians",
  "kolosser": "colossians",
  "1. thessalonicher": "1 thessalonians",
  "2. thessalonicher": "2 thessalonians",
  "1. timotheus": "1 timothy",
  "2. timotheus": "2 timothy",
  "titus": "titus",
  "philemon": "philemon",
  "hebräer": "hebrews",
  "jakobus": "james",
  "1. petrus": "1 peter",
  "2. petrus": "2 peter",
  "1. johannes": "1 john",
  "2. johannes": "2 john",
  "3. johannes": "3 john",
  "judas": "jude",
  "offenbarung": "revelation",
  "génesis": "genesis",
  "éxodo": "exodus",
  "levítico": "leviticus",
  "números": "numbers",
  "josué": "joshua",
  "jueces": "judges",
  "1 reyes": "1 kings",
  "2 reyes": "2 kings",
  "1 crónicas": "1 chronicles",
  "2 crónicas": "2 chronicles",
  "esdras": "ezra",
  "nehemías": "nehemiah",
  "salmos": "psalms",
  "proverbios": "proverbs",
  "eclesiastés": "ecclesiastes",
  "cantares": "song of solomon",
  "isaías": "isaiah",
  "jeremías": "jeremiah",
  "lamentaciones": "lamentations",
  "ezequiel": "ezekiel",
  "oseas": "hosea",
  "amós": "amos",
  "abdías": "obadiah",
  "jonás": "jonah",
  "miqueas": "micah",
  "nahúm": "nahum",
  "sofonías": "zephaniah",
  "hageo": "haggai",
  "zacarías": "zechariah",
  "malaquías": "malachi",
  "mateo": "matthew",
  "marcos": "mark",
  "lucas": "luke",
  "juan": "john",
  "hechos": "acts",
  "romanos": "romans",
  "1 corintios": "1 corinthians",
  "2 corintios": "2 corinthians",
  "gálatas": "galatians",
  "efesios": "ephesians",
  "filipenses": "philippians",
  "colosenses": "colossians",
  "1 tesalonicenses": "1 thessalonians",
  "2 tesalonicenses": "2 thessalonians",
  "filemón": "philemon",
  "hebreos": "hebrews",
  "santiago": "james",
  "1 pedro": "1 peter",
  "2 pedro": "2 peter",
  "1 juan": "1 john",
  "2 juan": "2 john",
  "3 juan": "3 john",
  "apocalipsis": "revelation",
  "genèse": "genesis",
  "exode": "exodus",
  "lévitique": "leviticus",
  "nombres": "numbers",
  "deutéronome": "deuteronomy",
  "juges": "judges",
  "1 rois": "1 kings",
  "2 rois": "2 kings",
  "1 chroniques": "1 chronicles",
  "2 chroniques": "2 chronicles",
  "néhémie": "nehemiah",
  "psaumes": "psalms",
  "psaume": "psalms",
  "proverbes": "proverbs",
  "ecclésiaste": "ecclesiastes",
  "cantique des cantiques": "song of solomon",
  "ésaïe": "isaiah",
  "jérémie": "jeremiah",
  "ézéchiel": "ezekiel",
  "osée": "hosea",
  "joël": "joel",
  "abdias": "obadiah",
  "jonas": "jonah",
  "michée": "micah",
  "sophonie": "zephaniah",
  "aggée": "haggai",
  "zacharie": "zechariah",
  "malachie": "malachi",
  "matthieu": "matthew",
  "marc": "mark",
  "luc": "luke",
  "jean": "john",
  "actes des apôtres": "acts",
  "romains": "romans",
  "1 corinthiens": "1 corinthians",
  "2 corinthiens": "2 corinthians",
  "galates": "galatians",
  "éphésiens": "ephesians",
  "philippiens": "philippians",
  "colossiens": "colossians",
  "1 thessaloniciens": "1 thessalonians",
  "2 thessaloniciens": "2 thessalonians",
  "1 timothée": "1 timothy",
  "2 timothée": "2 timothy",
  "tite": "titus",
  "philémon": "philemon",
  "hébreux": "hebrews",
  "jacques": "james",
  "1 pierre": "1 peter",
  "2 pierre": "2 peter",
  "1 jean": "1 john",
  "2 jean": "2 john",
  "3 jean": "3 john",
  "jude": "jude",
  "apocalypse": "revelation",
  "gênesis": "genesis",
  "êxodo": "exodus",
  "deuteronômio": "deuteronomy",
  "juízes": "judges",
  "rute": "ruth",
  "1 reis": "1 kings",
  "2 reis": "2 kings",
  "1 crônicas": "1 chronicles",
  "2 crônicas": "2 chronicles",
  "neemias": "nehemiah",
  "jó": "job",
  "provérbios": "proverbs",
  "eclesiastes": "ecclesiastes",
  "cântico dos cânticos": "song of solomon",
  "jeremias": "jeremiah",
  "lamentações": "lamentations",
  "oseias": "hosea",
  "obadias": "obadiah",
  "miquéias": "micah",
  "naum": "nahum",
  "habacuque": "habakkuk",
  "sofonias": "zephaniah",
  "ageu": "haggai",
  "zacarias": "zechariah",
  "malaquias": "malachi",
  "mateus": "matthew",
  "joão": "john",
  "atos": "acts",
  "1 coríntios": "1 corinthians",
  "2 coríntios": "2 corinthians",
  "efésios": "ephesians",
  "colossenses": "colossians",
  "1 tessalonicenses": "1 thessalonians",
  "2 tessalonicenses": "2 thessalonians",
  "1 timóteo": "1 timothy",
  "2 timóteo": "2 timothy",
  "filemom": "philemon",
  "hebreus": "hebrews",
  "tiago": "james",
  "1 joão": "1 john",
  "2 joão": "2 john",
  "3 joão": "3 john",
  "apocalipse": "revelation",
  "تكوين": "genesis",
  "خروج": "exodus",
  "لاويين": "leviticus",
  "عدد": "numbers",
  "تثنية": "deuteronomy",
  "يشوع": "joshua",
  "القضاة": "judges",
  "قضاة": "judges",
  "راعوث": "ruth",
  "1 صموئيل": "1 samuel",
  "2 صموئيل": "2 samuel",
  "1 الملوك": "1 kings",
  "2 الملوك": "2 kings",
  "1 ملوك": "1 kings",
  "2 ملوك": "2 kings",
  "1 أخبار الأيام": "1 chronicles",
  "2 أخبار الأيام": "2 chronicles",
  "عزرا": "ezra",
  "نحميا": "nehemiah",
  "أستير": "esther",
  "أيوب": "job",
  "المزامير": "psalms",
  "مزمور": "psalms",
  "مزامير": "psalms",
  "الأمثال": "proverbs",
  "أمثال": "proverbs",
  "الجامعة": "ecclesiastes",
  "جامعة": "ecclesiastes",
  "نشيد الأنشاد": "song of solomon",
  "نشيد الأناشيد": "song of solomon",
  "إشعياء": "isaiah",
  "إرميا": "jeremiah",
  "مراثي إرميا": "lamentations",
  "حزقيال": "ezekiel",
  "دانيال": "daniel",
  "هوشع": "hosea",
  "يوئيل": "joel",
  "عاموس": "amos",
  "عوبديا": "obadiah",
  "يونان": "jonah",
  "ميخا": "micah",
  "ناحوم": "nahum",
  "حبقوق": "habakkuk",
  "صفنيا": "zephaniah",
  "حجي": "haggai",
  "زكريا": "zechariah",
  "ملاخي": "malachi",
  "متى": "matthew",
  "مرقس": "mark",
  "لوقا": "luke",
  "يوحنا": "john",
  "أعمال الرسل": "acts",
  "أعمال": "acts",
  "رومية": "romans",
  "1 كورنثوس": "1 corinthians",
  "2 كورنثوس": "2 corinthians",
  "غلاطية": "galatians",
  "أفسس": "ephesians",
  "فيليبي": "philippians",
  "كولوسي": "colossians",
  "1 تسالونيكي": "1 thessalonians",
  "2 تسالونيكي": "2 thessalonians",
  "1 تيموثاوس": "1 timothy",
  "2 تيموثاوس": "2 timothy",
  "تيطس": "titus",
  "فليمون": "philemon",
  "عبرانيين": "hebrews",
  "يعقوب": "james",
  "1 بطرس": "1 peter",
  "2 بطرس": "2 peter",
  "1 يوحنا": "1 john",
  "2 يوحنا": "2 john",
  "3 يوحنا": "3 john",
  "يهوذا": "jude",
  "الرؤيا": "revelation",
  "رؤيا": "revelation",
  "उत्पत्ति": "genesis",
  "निर्गमन": "exodus",
  "लैव्यव्यवस्था": "leviticus",
  "लेवियतियुस": "leviticus",
  "गिनती": "numbers",
  "व्यवस्थाविवरण": "deuteronomy",
  "यहोशू": "joshua",
  "न्यायियों": "judges",
  "रूत": "ruth",
  "1 शमूएल": "1 samuel",
  "2 शमूएल": "2 samuel",
  "1 राजाओं": "1 kings",
  "2 राजाओं": "2 kings",
  "1 इतिहास": "1 chronicles",
  "2 इतिहास": "2 chronicles",
  "एज्रा": "ezra",
  "नहेम्याह": "nehemiah",
  "एस्तेर": "esther",
  "अय्यूब": "job",
  "भजन संहिता": "psalms",
  "नीतिवचन": "proverbs",
  "सभोपदेशक": "ecclesiastes",
  "श्रेष्ठगीत": "song of solomon",
  "यशायाह": "isaiah",
  "यिर्मयाह": "jeremiah",
  "विलापगीत": "lamentations",
  "यहेजकेल": "ezekiel",
  "दानिय्येल": "daniel",
  "होशे": "hosea",
  "योएल": "joel",
  "आमोस": "amos",
  "ओबद्याह": "obadiah",
  "योना": "jonah",
  "मीका": "micah",
  "नहूम": "nahum",
  "हबक्कूक": "habakkuk",
  "सपन्याह": "zephaniah",
  "हाग्गै": "haggai",
  "जकर्याह": "zechariah",
  "मलाकी": "malachi",
  "मत्ती": "matthew",
  "मरकुस": "mark",
  "लूका": "luke",
  "यूहन्ना": "john",
  "प्रेरितों के काम": "acts",
  "रोमियों": "romans",
  "1 कुरिन्थियों": "1 corinthians",
  "2 कुरिन्थियों": "2 corinthians",
  "गलातियों": "galatians",
  "इफिसियों": "ephesians",
  "फिलिप्पियों": "philippians",
  "कुलुस्सियों": "colossians",
  "1 थिस्सलुनीकियों": "1 thessalonians",
  "2 थिस्सलुनीकियों": "2 thessalonians",
  "1 तीमुथियुस": "1 timothy",
  "2 तीमुथियुस": "2 timothy",
  "तीतुस": "titus",
  "फिलेमोन": "philemon",
  "इब्रानियों": "hebrews",
  "याकूब": "james",
  "न्यायियो": "judges",
  "1 राजाओ": "1 kings",
  "2 राजाओ": "2 kings",
  "रोमियो": "romans",
  "1 कुरिन्थियो": "1 corinthians",
  "2 कुरिन्थियो": "2 corinthians",
  "गलातियो": "galatians",
  "इफिसियो": "ephesians",
  "कुलुस्सियो": "colossians",
  "1 थिस्सलुनीकियो": "1 thessalonians",
  "2 थिस्सलुनीकियो": "2 thessalonians",
  "इब्रानियो": "hebrews",
  "1 पतरस": "1 peter",
  "2 पतरस": "2 peter",
  "1 यूहन्ना": "1 john",
  "2 यूहन्ना": "2 john",
  "3 यूहन्ना": "3 john",
  "यहूदा": "jude",
  "प्रकाशितवाक्य": "revelation",
  "бытие": "genesis",
  "исход": "exodus",
  "левит": "leviticus",
  "числа": "numbers",
  "второзаконие": "deuteronomy",
  "иисус навин": "joshua",
  "судьи": "judges",
  "руфь": "ruth",
  "1 царств": "1 samuel",
  "2 царств": "2 samuel",
  "3 царств": "1 kings",
  "4 царств": "2 kings",
  "1 паралипоменон": "1 chronicles",
  "2 паралипоменон": "2 chronicles",
  "ездра": "ezra",
  "неемия": "nehemiah",
  "есфирь": "esther",
  "иов": "job",
  "псалтирь": "psalms",
  "притчи": "proverbs",
  "екклесиаст": "ecclesiastes",
  "песня песней": "song of solomon",
  "песни песней": "song of solomon",
  "исаия": "isaiah",
  "иеремия": "jeremiah",
  "плач иеремии": "lamentations",
  "иезекиль": "ezekiel",
  "даниил": "daniel",
  "осия": "hosea",
  "иоиль": "joel",
  "амос": "amos",
  "авдий": "obadiah",
  "иона": "jonah",
  "михей": "micah",
  "наум": "nahum",
  "аввакум": "habakkuk",
  "софония": "zephaniah",
  "аггей": "haggai",
  "захария": "zechariah",
  "малахия": "malachi",
  "матфей": "matthew",
  "марк": "mark",
  "лука": "luke",
  "иоанн": "john",
  "деяния апостолов": "acts",
  "деяния": "acts",
  "римлянам": "romans",
  "1 коринфянам": "1 corinthians",
  "2 коринфянам": "2 corinthians",
  "галатам": "galatians",
  "ефесянам": "ephesians",
  "филиппийцам": "philippians",
  "колоссянам": "colossians",
  "1 фессалоникийцам": "1 thessalonians",
  "2 фессалоникийцам": "2 thessalonians",
  "1 тимофею": "1 timothy",
  "2 тимофею": "2 timothy",
  "титу": "titus",
  "филимону": "philemon",
  "евреям": "hebrews",
  "иаков": "james",
  "1 петра": "1 peter",
  "2 петра": "2 peter",
  "1 иоанна": "1 john",
  "2 иоанна": "2 john",
  "3 иоанна": "3 john",
  "иуда": "jude",
  "откровение": "revelation",
  "ин": "john",
  "мф": "matthew",
  "мк": "mark",
  "лк": "luke",
  "пс": "psalms",
  "рим": "romans",
  "быт": "genesis",
  "ис": "isaiah",
  "откр": "revelation",
  "деян": "acts",
  "гал": "galatians",
  "еф": "ephesians",
  "кол": "colossians",
  "евр": "hebrews",
  "иак": "james",
  "флп": "philippians",
  "флм": "philemon",
  "иёв": "job",
  "бытия": "genesis",
  "исхода": "exodus",
  "левита": "leviticus",
  "числ": "numbers",
  "второзакония": "deuteronomy",
  "руфи": "ruth",
  "псалтири": "psalms",
  "притч": "proverbs",
  "екклесиаста": "ecclesiastes",
  "исаии": "isaiah",
  "иеремии": "jeremiah",
  "иезекиля": "ezekiel",
  "даниила": "daniel",
  "осии": "hosea",
  "иоиля": "joel",
  "ионы": "jonah",
  "михея": "micah",
  "наума": "nahum",
  "аввакума": "habakkuk",
  "софонии": "zephaniah",
  "аггея": "haggai",
  "захарии": "zechariah",
  "малахии": "malachi",
  "матфея": "matthew",
  "марка": "mark",
  "луки": "luke",
  "иоанна": "john",
  "деяний": "acts",
  "иакова": "james",
  "иуды": "jude",
  "откровения": "revelation",
  "1-я царств": "1 samuel",
  "2-я царств": "2 samuel",
  "3-я царств": "1 kings",
  "4-я царств": "2 kings",
  "1-я паралипоменон": "1 chronicles",
  "2-я паралипоменон": "2 chronicles",
  "1-е коринфянам": "1 corinthians",
  "2-е коринфянам": "2 corinthians",
  "1-е фессалоникийцам": "1 thessalonians",
  "2-е фессалоникийцам": "2 thessalonians",
  "1-е тимофею": "1 timothy",
  "2-е тимофею": "2 timothy",
  "1-е петра": "1 peter",
  "2-е петра": "2 peter",
  "1-е иоанна": "1 john",
  "2-е иоанна": "2 john",
  "3-е иоанна": "3 john",
  "2-я петра": "2 peter",
  "创世记": "genesis",
  "创世纪": "genesis",
  "出埃及记": "exodus",
  "利未记": "leviticus",
  "民数记": "numbers",
  "申命记": "deuteronomy",
  "约书亚记": "joshua",
  "士师记": "judges",
  "路得记": "ruth",
  "撒母耳记上": "1 samuel",
  "撒母耳记下": "2 samuel",
  "列王纪上": "1 kings",
  "列王纪下": "2 kings",
  "历代志上": "1 chronicles",
  "历代志下": "2 chronicles",
  "以斯拉记": "ezra",
  "尼希米记": "nehemiah",
  "以斯帖记": "esther",
  "约伯记": "job",
  "诗篇": "psalms",
  "箴言": "proverbs",
  "传道书": "ecclesiastes",
  "雅歌": "song of solomon",
  "以赛亚书": "isaiah",
  "耶利米书": "jeremiah",
  "耶利米哀歌": "lamentations",
  "以西结书": "ezekiel",
  "但以理书": "daniel",
  "何西阿书": "hosea",
  "约珥书": "joel",
  "阿摩司书": "amos",
  "俄巴底亚书": "obadiah",
  "约拿书": "jonah",
  "弥迦书": "micah",
  "那鸿书": "nahum",
  "哈巴谷书": "habakkuk",
  "西番雅书": "zephaniah",
  "哈该书": "haggai",
  "撒迦利亚书": "zechariah",
  "玛拉基书": "malachi",
  "马太福音": "matthew",
  "马可福音": "mark",
  "路加福音": "luke",
  "约翰福音": "john",
  "使徒行传": "acts",
  "罗马书": "romans",
  "哥林多前书": "1 corinthians",
  "哥林多后书": "2 corinthians",
  "加拉太书": "galatians",
  "以弗所书": "ephesians",
  "腓立比书": "philippians",
  "歌罗西书": "colossians",
  "帖撒罗尼迦前书": "1 thessalonians",
  "帖撒罗尼迦后书": "2 thessalonians",
  "提摩太前书": "1 timothy",
  "提摩太后书": "2 timothy",
  "提多书": "titus",
  "腓利门书": "philemon",
  "希伯来书": "hebrews",
  "雅各书": "james",
  "彼得前书": "1 peter",
  "彼得后书": "2 peter",
  "约翰一书": "1 john",
  "约翰二书": "2 john",
  "约翰三书": "3 john",
  "犹大书": "jude",
  "启示录": "revelation",
  "出埃及纪": "exodus",
  "利未纪": "leviticus",
  "民数纪": "numbers",
  "申命纪": "deuteronomy",
  "约书亚纪": "joshua",
  "士师纪": "judges",
  "路得纪": "ruth",
  "撒母耳纪上": "1 samuel",
  "撒母耳纪下": "2 samuel",
  "列王记上": "1 kings",
  "列王记下": "2 kings",
  "以斯拉纪": "ezra",
  "尼希米纪": "nehemiah",
  "以斯帖纪": "esther",
  "约伯纪": "job",
  "玛窦福音": "matthew",
  "马尔谷福音": "mark",
  "若望福音": "john",
  "宗徒大事录": "acts",
  "默示录": "revelation",
  "格林多前书": "1 corinthians",
  "格林多后书": "2 corinthians",
  "若望一书": "1 john",
  "若望二书": "2 john",
  "若望三书": "3 john",
  "雅各伯书": "james",
  "犹达书": "jude",
  "창세기": "genesis",
  "출애굽기": "exodus",
  "레위기": "leviticus",
  "민수기": "numbers",
  "신명기": "deuteronomy",
  "여호수아": "joshua",
  "사사기": "judges",
  "룻기": "ruth",
  "사무엘상": "1 samuel",
  "사무엘하": "2 samuel",
  "열왕기상": "1 kings",
  "열왕기하": "2 kings",
  "역대상": "1 chronicles",
  "역대하": "2 chronicles",
  "에스라": "ezra",
  "느헤미야": "nehemiah",
  "에스더": "esther",
  "욥기": "job",
  "시편": "psalms",
  "잠언": "proverbs",
  "전도서": "ecclesiastes",
  "아가": "song of solomon",
  "이사야": "isaiah",
  "예레미야": "jeremiah",
  "예레미야애가": "lamentations",
  "예레미야 애가": "lamentations",
  "에스겔": "ezekiel",
  "다니엘": "daniel",
  "호세아": "hosea",
  "요엘": "joel",
  "아모스": "amos",
  "오바댜": "obadiah",
  "요나": "jonah",
  "미가": "micah",
  "나훔": "nahum",
  "하박국": "habakkuk",
  "스바냐": "zephaniah",
  "학개": "haggai",
  "스가랴": "zechariah",
  "말라기": "malachi",
  "마태복음": "matthew",
  "마가복음": "mark",
  "누가복음": "luke",
  "요한복음": "john",
  "사도행전": "acts",
  "로마서": "romans",
  "고린도전서": "1 corinthians",
  "고린도후서": "2 corinthians",
  "갈라디아서": "galatians",
  "에베소서": "ephesians",
  "빌립보서": "philippians",
  "골로새서": "colossians",
  "데살로니가전서": "1 thessalonians",
  "데살로니가후서": "2 thessalonians",
  "디모데전서": "1 timothy",
  "디모데후서": "2 timothy",
  "디도서": "titus",
  "빌레몬서": "philemon",
  "히브리서": "hebrews",
  "야고보서": "james",
  "베드로전서": "1 peter",
  "베드로후서": "2 peter",
  "요한일서": "1 john",
  "요한이서": "2 john",
  "요한삼서": "3 john",
  "유다서": "jude",
  "요한계시록": "revelation",
  "계시록": "revelation",
  "애가": "lamentations",
  "행전": "acts",
};
