name: Commitlint

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
